{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Billme x Talaadthai",
    "description" : "API for <b>Talaadthai</b>\n<br>\n<h2>CHANGELOG</h2>\n<h3>1.0.6</h3>\n- added `Delete Invoice API`\n    \n<h3>1.0.5</h3>\n- updated json body of `Create Receipt API`\n    - added field `invoice_id`\n    - removed field `name`\n\n<h3>1.0.4</h3>\n- updated enum of `InvoiceStatus` of `List Customer Invoices API`\n\n<h3>1.0.3</h3>\n- added new `Customer APIs`\n- added new enum value `market_insurance` of `Invoice Type`  \n- updated example request of `Create Receipt API`\n\n<h3>1.0.2</h3>\n- added header `x-api-key`\n- added field `issue_date` on schema `CreatingInvoice`\n\n<h3>1.0.1</h3>\n- added required field `customer.tms_id`\n- added optional field `customer.telephone`\n- renamed field `customer.code` to `customer.number`\n",
    "version" : "1.0.6"
  },
  "servers" : [ {
    "url" : "https://talaadthai.billme.co.th"
  } ],
  "tags" : [ {
    "name" : "Invoices",
    "description" : "Invoices API"
  }, {
    "name" : "Receipts",
    "description" : "Receipts API"
  }, {
    "name" : "Customers",
    "description" : "Customers API"
  } ],
  "paths" : {
    "/api/invoices" : {
      "post" : {
        "tags" : [ "Invoices" ],
        "parameters" : [ {
          "in" : "header",
          "name" : "x-api-key",
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          },
          "required" : true,
          "description" : "Api key as a authorization",
          "example" : "5a5e2a77-bfb7-4ff8-9cd5-9ecd54669c57"
        } ],
        "summary" : "Created invoice",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/StatementOfInvoice"
              },
              "example" : {
                "customer" : {
                  "tms_id" : "mock_tms_id",
                  "number" : "6104031-0010",
                  "name" : "หจก.พี.โอแมงโก สำนักงานใหญ่",
                  "tax_number" : null,
                  "branch_number" : null,
                  "telephone" : null,
                  "type" : "corporate",
                  "address" : {
                    "street_number" : "17/155 ถ.ปทุมกรุงเพท",
                    "sub_district" : "ต.บางปรอก",
                    "district" : "อ.เมืองปทุมธานี",
                    "province" : "จ.ปทุมธานี",
                    "post_code" : "12000"
                  }
                },
                "invoices" : [ {
                  "number" : "INE620300959",
                  "issue_date" : "31-04-2019",
                  "description" : "ค่าไฟฟ้า 25 กพ-24 มีค 62#2818-2855",
                  "total_amount" : 243.46,
                  "vat_amount" : 17.04,
                  "gross_amount" : 260.5
                } ],
                "stall_numbers" : [ "SF17-002" ],
                "withholding_taxes" : [ {
                  "rate" : 0.05,
                  "amount" : 1848.0
                }, {
                  "rate" : 0.03,
                  "amount" : 151.4
                } ],
                "issue_date" : "10-04-2019",
                "due_date" : "17-04-2019",
                "rental_amount" : 36960.0,
                "service_amount" : 6967.06,
                "vat_amount" : 487.69,
                "total_amount" : 7454.75,
                "gross_amount" : 42415.35,
                "thai_baht" : "สี่หมื่นสองพันสี่ร้อยสิบห้าบาทสามสิบห้าสตางค์"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "key" : {
                      "type" : "string",
                      "description" : "created invoice id."
                    }
                  }
                },
                "example" : {
                  "key" : "2a49794984a24725abedffcef9b6c849"
                }
              }
            },
            "description" : "Successful operation"
          },
          "400" : {
            "description" : "Invalid input"
          }
        }
      }
    },
    "/api/invoices/{id}" : {
      "get" : {
        "tags" : [ "Invoices" ],
        "summary" : "Get invoice by id",
        "parameters" : [ {
          "in" : "header",
          "name" : "x-api-key",
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          },
          "required" : true,
          "description" : "Api key as a authorization",
          "example" : "5a5e2a77-bfb7-4ff8-9cd5-9ecd54669c57"
        }, {
          "in" : "path",
          "name" : "id",
          "description" : "id of invoice to return",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "examples" : {
            "id" : {
              "value" : "533e999a7ff04e3caa2b9306b56b3e3e"
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/InvoiceDetail"
                },
                "example" : {
                  "id" : "533e999a7ff04e3caa2b9306b56b3e3e",
                  "customer" : {
                    "tms_id" : "mock_tms_id",
                    "number" : "6104031-0010",
                    "type" : "corporate",
                    "name" : "หจก.พี.โอ.แมงโก สำนักงานใหญ่",
                    "alias" : null,
                    "tax_number" : null,
                    "branch_number" : "00000",
                    "telephone" : 21234567,
                    "emails" : [ ],
                    "address" : {
                      "line_one" : "17/155 ถ.ปทุมกรุงเทพ",
                      "line_two" : "ต.บางปรอก อ.เมืองปทุมธานี จ.ปทุมธานี 12000",
                      "street_number" : "17/155 ถ.ปทุมกรุงเทพ",
                      "sub_district" : "ต.บางปรอก",
                      "district" : "อ.เมืองปทุมธานี",
                      "province" : "จ.ปทุมธานี",
                      "post_code" : "12000"
                    }
                  },
                  "seller" : {
                    "name" : "บริษัท ไทย แอ็กโกร เอ็กซเชนจ์ จำกัด",
                    "logo" : "https://storage.googleapis.com/billhub/yeast/production/profiles/5b377da2bfe14b748f547a6f61937786/Billbox.jpg",
                    "tax_number" : 1.05537125845E11,
                    "branch_number" : "00000",
                    "telephone" : "0-2908-4490-9",
                    "email" : "talaadthai@billme.co.th",
                    "address" : {
                      "line_one" : "31 หมู่ 9 ถ.พหลโยธิน กม.42",
                      "line_two" : "ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
                      "street_number" : "31 หมู่ 9 ถ.พหลโยธิน กม.4",
                      "sub_district" : "ต.คลองหนึ่ง",
                      "district" : "อ.คลองหลวง",
                      "province" : "จ.ปทุมธานี",
                      "post_code" : "12120"
                    }
                  },
                  "name" : "ใบแจ้งค่าบริการ 2019-09-19",
                  "number" : "INV201909190001",
                  "items" : [ {
                    "description" : "ใบแจ้งค่าบริการ 2019-09-19",
                    "quantity" : 1,
                    "total_item_price" : 42415.35
                  } ],
                  "payment_methods" : [ {
                    "name" : "บริษัท ไทย แอ็กโกร เอ็กซเชนจ์ จำกัด",
                    "method_type" : "kbank_payment_qrcode",
                    "number" : "123-456-7890",
                    "logo" : "https://storage.googleapis.com/billme-static/billme/bank-logo/logo-bank-kbank-payment-qrcode.png"
                  } ],
                  "documents" : {
                    "invoice" : "https://storage.googleapis.com/billhub/staging/invoices/F754D3C3D5C05616ADE2BCD39A058AD4/INV62000028.pdf",
                    "receipt" : null,
                    "tax_invoice" : null
                  },
                  "issue_date" : "2019-06-14 13:26:49",
                  "due_date" : "2019-06-21 13:25:28",
                  "remark" : "",
                  "status" : "pending_payment",
                  "discount" : null,
                  "vat" : null,
                  "withholding_tax" : null,
                  "net_amount" : 42415.35,
                  "items_amount" : 42415.35,
                  "total_amount" : 7454.75,
                  "gross_amount" : 42415.35,
                  "reject_reasons" : [ ],
                  "attachments" : [ ]
                }
              }
            }
          },
          "404" : {
            "description" : "Invoice not found"
          }
        }
      },
      "delete" : {
        "tags" : [ "Invoices" ],
        "parameters" : [ {
          "in" : "header",
          "name" : "x-api-key",
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          },
          "required" : true,
          "description" : "Api key as a authorization",
          "example" : "5a5e2a77-bfb7-4ff8-9cd5-9ecd54669c57"
        }, {
          "in" : "path",
          "name" : "id",
          "description" : "id of invoice to delete",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "examples" : {
            "id" : {
              "value" : "533e999a7ff04e3caa2b9306b56b3e3e"
            }
          }
        } ],
        "responses" : {
          "204" : {
            "description" : "Successful operation"
          }
        }
      }
    },
    "/api/receipts" : {
      "post" : {
        "tags" : [ "Receipts" ],
        "parameters" : [ {
          "in" : "header",
          "name" : "x-api-key",
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          },
          "required" : true,
          "description" : "Api key as a authorization",
          "example" : "5a5e2a77-bfb7-4ff8-9cd5-9ecd54669c57"
        } ],
        "summary" : "Created receipt",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CreatingReceipt"
              },
              "example" : {
                "invoice_id" : "171432daa95d48d38187d739491f7ef5",
                "number" : 620300846,
                "customer" : {
                  "tms_id" : "mock-tms-id",
                  "name" : "ณฐพงศ์ ลิมปนเวทยานนท์",
                  "number" : "6203052-0006",
                  "tax_number" : null,
                  "branch_number" : null,
                  "telephone" : null,
                  "type" : "individual",
                  "address" : {
                    "street_number" : "391 ซ.พระรามที่ 2",
                    "sub_district" : "แขวงแสมดำ",
                    "district" : "เขตบางขุนเทียน",
                    "province" : "กรุงเทพฯ",
                    "post_code" : "10150"
                  }
                },
                "issue_date" : "08-09-2019",
                "items" : [ {
                  "is_exemption" : false,
                  "description" : "ค่าเช่า",
                  "invoice_number" : "INV620900085",
                  "invoice_type" : "rental",
                  "issue_date" : "08-09-2019",
                  "amount" : 304.0
                }, {
                  "is_exemption" : false,
                  "description" : "ค่าเช่า",
                  "invoice_number" : "RC620901291",
                  "invoice_type" : "rental",
                  "issue_date" : "08-09-2019",
                  "amount" : 4800.0
                }, {
                  "is_exemption" : true,
                  "description" : "ค่าไฟฟ้า",
                  "invoice_number" : "INE620801207",
                  "invoice_type" : "electric_meters",
                  "issue_date" : "08-08-2019",
                  "amount" : 3873.0
                } ],
                "gross_amount" : 8977.0,
                "vat_exemption_amount" : 5104.0,
                "vat_payable_amount" : 3619.63,
                "vat_amount" : 253.37,
                "thai_baht" : "แปดพันเก้าร้อยเจ็ดสิบเจ็ดบาทถ้วน"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "key" : {
                      "type" : "string",
                      "description" : "created receipt id."
                    }
                  }
                },
                "example" : {
                  "key" : "1e77297eb4bc4db6a65999c7c8fc566f"
                }
              }
            },
            "description" : "Successful operation"
          },
          "400" : {
            "description" : "Invalid input"
          }
        }
      }
    },
    "/api/receipts/{id}" : {
      "get" : {
        "tags" : [ "Receipts" ],
        "summary" : "Get receipt by id",
        "parameters" : [ {
          "in" : "header",
          "name" : "x-api-key",
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          },
          "required" : true,
          "description" : "Api key as a authorization",
          "example" : "5a5e2a77-bfb7-4ff8-9cd5-9ecd54669c57"
        }, {
          "name" : "id",
          "in" : "path",
          "description" : "id of receipt to return",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "examples" : {
            "id" : {
              "value" : "1e77297eb4bc4db6a65999c7c8fc566f"
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ReceiptDetail"
                },
                "example" : {
                  "id" : "1e77297eb4bc4db6a65999c7c8fc566f",
                  "customer" : {
                    "tms_id" : "mock_tms_id",
                    "name" : "ณฐพงศ์ ลิมปนเวทยานนท์",
                    "number" : "6203052-0006",
                    "tax_number" : null,
                    "branch_number" : null,
                    "type" : "individual",
                    "telephone" : 21234567,
                    "emails" : [ ],
                    "address" : {
                      "street_number" : "391 ซ.พระรามที่ 2",
                      "sub_district" : "แขวงแสมดำ",
                      "district" : "เขตบางขุนเทียน",
                      "province" : "กรุงเทพฯ",
                      "post_code" : "10150"
                    }
                  },
                  "seller" : {
                    "name" : "บริษัท ไทย แอ็กโกร เอ็กซเชนจ์ จำกัด",
                    "logo" : "https://storage.googleapis.com/billhub/yeast/production/profiles/5b377da2bfe14b748f547a6f61937786/Billbox.jpg",
                    "tax_number" : 1.05537125845E11,
                    "branch_number" : "00000",
                    "telephone" : "0-2908-4490-9",
                    "email" : "talaadthai@billme.co.th",
                    "address" : {
                      "line_one" : "31 หมู่ 9 ถ.พหลโยธิน กม.42",
                      "line_two" : "ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
                      "street_number" : "31 หมู่ 9 ถ.พหลโยธิน กม.4",
                      "sub_district" : "ต.คลองหนึ่ง",
                      "district" : "อ.คลองหลวง",
                      "province" : "จ.ปทุมธานี",
                      "post_code" : "12120"
                    }
                  },
                  "name" : "ใบเสร็จ",
                  "number" : "RCP1810240001",
                  "items" : [ {
                    "description" : "ค่าบริการ 10-09-2019",
                    "quantity" : 1,
                    "total_item_price" : 42415.35
                  } ],
                  "issue_date" : "2019-10-24 18:44:46",
                  "remark" : "-",
                  "net_amount" : 42415.35,
                  "items_amount" : 42415.35,
                  "total_amount" : 42415.35,
                  "gross_amount" : 42415.35
                }
              }
            }
          },
          "404" : {
            "description" : "Receipt not found"
          }
        }
      }
    },
    "/api/customers" : {
      "get" : {
        "tags" : [ "Customers" ],
        "summary" : "List all customers or search by tms_id",
        "parameters" : [ {
          "in" : "header",
          "name" : "x-api-key",
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          },
          "required" : true,
          "description" : "Api key as a authorization",
          "example" : "5a5e2a77-bfb7-4ff8-9cd5-9ecd54669c57"
        }, {
          "in" : "query",
          "name" : "tms_id",
          "schema" : {
            "type" : "string"
          },
          "required" : false,
          "description" : "tms id",
          "example" : "mock-tms-id"
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "customers" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/CustomerResponse"
                      }
                    }
                  }
                },
                "example" : {
                  "customers" : [ {
                    "id" : "17a4a05f2f10ca0f10cbee85f2f10344d86d8b",
                    "tms_id" : "9714",
                    "name" : "นายไพรัช แสงมณี",
                    "telephone" : "081-906-9317",
                    "street_number" : "90/0634 หมู่ 6",
                    "sub_district" : "ต.คลองหนึ่ง",
                    "district" : "อ.คลองหลวง",
                    "province" : "จ.ปทุมธานี",
                    "postal_code" : "12120"
                  } ]
                }
              }
            }
          }
        }
      }
    },
    "/api/customers/{id}/invoices" : {
      "get" : {
        "tags" : [ "Customers" ],
        "parameters" : [ {
          "in" : "path",
          "name" : "id",
          "description" : "id of customer",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "examples" : {
            "id" : {
              "value" : "17a4a05f2f10ca0f10cbee85f2f10344d86d8b"
            }
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "invoices" : {
                      "type" : "array",
                      "items" : {
                        "$ref" : "#/components/schemas/ShareableInvoiceResponse"
                      }
                    }
                  }
                },
                "example" : {
                  "invoices" : [ {
                    "invoice_id" : "a7b60dc9ae49fdcf22492447aaefbf09",
                    "customer_id" : "17a4a05f2f10ca0f10cbee85f2f10344d86d8b",
                    "shareable_url" : "https://staging-talaadthai.billme.co.th/81b462904970ae4da2c782aa6de474",
                    "invoice" : {
                      "customer" : {
                        "name" : "นามสมชัย เย็นศุข",
                        "tms_id" : "mock-tms-id"
                      },
                      "status" : "pending_payment",
                      "number" : "8602001-0060",
                      "issue_date" : "01-10-2019",
                      "due_date" : "30-10-2019",
                      "gross_amount" : 2400.0
                    }
                  } ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "CreatingAddress" : {
        "type" : "object",
        "properties" : {
          "street_number" : {
            "type" : "string"
          },
          "sub_distrcit" : {
            "type" : "string"
          },
          "distrcit" : {
            "type" : "string"
          },
          "province" : {
            "type" : "string"
          },
          "post_code" : {
            "type" : "string"
          }
        }
      },
      "CreatingCustomer" : {
        "type" : "object",
        "properties" : {
          "tms_id" : {
            "type" : "string"
          },
          "number" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "tax_number" : {
            "type" : "string",
            "nullable" : true
          },
          "branch_number" : {
            "type" : "string",
            "nullable" : true
          },
          "type" : {
            "type" : "string",
            "nullable" : true
          },
          "telephone" : {
            "type" : "string",
            "nullable" : true
          },
          "address" : {
            "$ref" : "#/components/schemas/CreatingAddress"
          }
        }
      },
      "CreatingWithholdingTax" : {
        "type" : "object",
        "properties" : {
          "rate" : {
            "type" : "number",
            "format" : "double"
          },
          "amount" : {
            "type" : "number",
            "format" : "double"
          }
        }
      },
      "CreatingInvoice" : {
        "type" : "object",
        "properties" : {
          "number" : {
            "type" : "string"
          },
          "issue_date" : {
            "type" : "string",
            "format" : "date"
          },
          "description" : {
            "type" : "string"
          },
          "total_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "vat_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "gross_amount" : {
            "type" : "number",
            "format" : "double"
          }
        }
      },
      "CreatingReceiptItem" : {
        "type" : "object",
        "properties" : {
          "invoice_type" : {
            "type" : "string",
            "enum" : [ "rental", "market", "market_insurance", "electric_meters", "water_meters", "others" ],
            "description" : "ค่าเช่า, ค่าระบบตลาด, ค่าประกันแผงค้า, ค่าค้ำประกันมิเตอร์ไฟฟ้า, ค่าค้ำประกันมิเตอร์ประปา, อื่นๆ"
          },
          "is_exemption" : {
            "type" : "boolean"
          },
          "description" : {
            "type" : "string"
          },
          "invoice_number" : {
            "type" : "string"
          },
          "issue_date" : {
            "type" : "string",
            "format" : "date"
          },
          "amount" : {
            "type" : "number",
            "format" : "double"
          }
        }
      },
      "CreatingReceipt" : {
        "type" : "object",
        "properties" : {
          "invoice_id" : {
            "type" : "string"
          },
          "number" : {
            "type" : "string"
          },
          "customer" : {
            "type" : "object",
            "properties" : {
              "tms_id" : {
                "type" : "string"
              },
              "tax_number" : {
                "type" : "string",
                "nullable" : true
              },
              "branch_number" : {
                "type" : "string",
                "nullable" : true
              },
              "number" : {
                "type" : "string"
              },
              "telephone" : {
                "type" : "string",
                "nullable" : true
              }
            }
          },
          "issue_date" : {
            "type" : "string",
            "format" : "date"
          },
          "items" : {
            "$ref" : "#/components/schemas/CreatingReceiptItem"
          },
          "gross_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "thai_baht" : {
            "type" : "string"
          },
          "vat_exemption_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "vat_payable_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "vat_amount" : {
            "type" : "number",
            "format" : "double"
          }
        }
      },
      "StatementOfInvoice" : {
        "type" : "object",
        "properties" : {
          "customer" : {
            "$ref" : "#/components/schemas/CreatingCustomer"
          },
          "invoices" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/CreatingInvoice"
            }
          },
          "stall_numbers" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "withholding_taxes" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/CreatingWithholdingTax"
            }
          },
          "issue_date" : {
            "type" : "string",
            "format" : "date"
          },
          "due_date" : {
            "type" : "string",
            "format" : "date"
          },
          "rental_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "service_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "vat_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "total_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "gross_amount" : {
            "type" : "number",
            "format" : "double"
          },
          "thai_baht" : {
            "type" : "string"
          }
        }
      },
      "Address" : {
        "type" : "object",
        "properties" : {
          "line_one" : {
            "type" : "string"
          },
          "line_two" : {
            "type" : "string"
          },
          "street_number" : {
            "type" : "string"
          },
          "sub_distrcit" : {
            "type" : "string"
          },
          "district" : {
            "type" : "string"
          },
          "province" : {
            "type" : "string"
          },
          "post_code" : {
            "type" : "string"
          }
        }
      },
      "Customer" : {
        "type" : "object",
        "properties" : {
          "tms_id" : {
            "type" : "string"
          },
          "number" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "alias" : {
            "type" : "string",
            "nullable" : true
          },
          "tax_number" : {
            "type" : "string",
            "nullable" : true
          },
          "branch_number" : {
            "type" : "string"
          },
          "telephone" : {
            "type" : "string",
            "nullable" : true
          },
          "emails" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "address" : {
            "$ref" : "#/components/schemas/Address"
          }
        }
      },
      "Seller" : {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "logo" : {
            "type" : "string"
          },
          "tax_number" : {
            "type" : "string"
          },
          "branch_number" : {
            "type" : "string"
          },
          "telephone" : {
            "type" : "string",
            "nullable" : true
          },
          "email" : {
            "type" : "string"
          },
          "address" : {
            "$ref" : "#/components/schemas/Address"
          }
        }
      },
      "Item" : {
        "type" : "object",
        "properties" : {
          "description" : {
            "type" : "string"
          },
          "quantity" : {
            "type" : "number",
            "format" : "double"
          },
          "total_item_price" : {
            "type" : "number",
            "format" : "double"
          }
        }
      },
      "PaymentMethod" : {
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "method_type" : {
            "type" : "string"
          },
          "number" : {
            "type" : "string"
          },
          "logo" : {
            "type" : "string"
          }
        }
      },
      "InvoiceDetail" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "customer" : {
            "$ref" : "#/components/schemas/Customer"
          },
          "seller" : {
            "$ref" : "#/components/schemas/Seller"
          },
          "name" : {
            "type" : "string",
            "nullable" : true
          },
          "number" : {
            "type" : "string"
          },
          "items" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Item"
            }
          },
          "payment_methods" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/PaymentMethod"
            }
          },
          "file_url" : {
            "type" : "string"
          },
          "issue_date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "due_date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "remark" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "net_amount" : {
            "type" : "string"
          },
          "items_amount" : {
            "type" : "string"
          },
          "total_amount" : {
            "type" : "string"
          },
          "gross_amount" : {
            "type" : "string"
          },
          "reject_reasons" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      },
      "ReceiptDetail" : {
        "type" : "object",
        "properties" : {
          "customer" : {
            "$ref" : "#/components/schemas/Customer"
          },
          "seller" : {
            "$ref" : "#/components/schemas/Seller"
          },
          "name" : {
            "type" : "string",
            "nullable" : true
          },
          "number" : {
            "type" : "string"
          },
          "items" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Item"
            }
          },
          "issue_date" : {
            "type" : "string",
            "format" : "date-time"
          },
          "remark" : {
            "type" : "string"
          },
          "net_amount" : {
            "type" : "string"
          },
          "items_amount" : {
            "type" : "string"
          },
          "total_amount" : {
            "type" : "string"
          },
          "gross_amount" : {
            "type" : "string"
          },
          "file_url" : {
            "type" : "string"
          }
        }
      },
      "CustomerResponse" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "tms_id" : {
            "type" : "string",
            "nullable" : true
          },
          "name" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          },
          "telephone" : {
            "type" : "string"
          },
          "street_number" : {
            "type" : "string"
          },
          "sub_district" : {
            "type" : "string"
          },
          "district" : {
            "type" : "string"
          },
          "province" : {
            "type" : "string"
          },
          "postal_code" : {
            "type" : "string"
          }
        }
      },
      "ShareableInvoiceResponse" : {
        "type" : "object",
        "properties" : {
          "invoice_id" : {
            "type" : "string"
          },
          "customer_id" : {
            "type" : "string",
            "nullable" : true
          },
          "shareable_url" : {
            "type" : "string"
          },
          "invoice" : {
            "type" : "object",
            "properties" : {
              "customer" : {
                "type" : "object",
                "properties" : {
                  "name" : {
                    "type" : "string"
                  },
                  "tms_id" : {
                    "type" : "string",
                    "nullable" : true
                  }
                }
              },
              "status" : {
                "type" : "string",
                "enum" : [ "created", "pending_payment", "pending_approval", "paid", "report" ],
                "description" : "กำลังส่ง, ยังไม่ชำระ, ตรวจสอบการชำระ, ชำระแล้ว, ถูกปฏิเสธ"
              },
              "number" : {
                "type" : "string"
              },
              "issue_date" : {
                "type" : "string",
                "format" : "date"
              },
              "due_date" : {
                "type" : "string",
                "format" : "date"
              },
              "gross_amount" : {
                "type" : "number",
                "format" : "double"
              }
            }
          }
        }
      }
    }
  }
}