{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "measurability apis staging",
    "contact" : { },
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "https://staging1ms.embibe.com/dsl/cqi_measurability",
    "variables" : { }
  } ],
  "paths" : {
    "/store_validated_schema" : {
      "post" : {
        "tags" : [ "Misc" ],
        "summary" : "store validated schema",
        "operationId" : "storevalidatedschema",
        "parameters" : [ ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/storevalidatedschemarequest"
              },
              "example" : {
                "event_code" : "r-shp-21",
                "event_metadata" : [ {
                  "field_name" : "event_name",
                  "is_null_allowed" : false,
                  "is_optional" : false,
                  "type" : "string",
                  "value" : "exams names & icons"
                }, {
                  "field_name" : "event_type",
                  "is_null_allowed" : false,
                  "is_optional" : false,
                  "type" : "string",
                  "value" : "click"
                }, {
                  "field_name" : "log_type",
                  "is_null_allowed" : false,
                  "is_optional" : true,
                  "type" : "string",
                  "value" : "search-home-page"
                }, {
                  "field_name" : "nav_element",
                  "is_null_allowed" : false,
                  "is_optional" : false,
                  "type" : "string",
                  "value" : "bottom exam bar"
                } ],
                "extra_params" : [ {
                  "field_name" : "exam_selected",
                  "is_null_allowed" : false,
                  "is_optional" : false,
                  "type" : "string"
                }, {
                  "field_name" : "user_query",
                  "is_null_allowed" : false,
                  "is_optional" : true,
                  "type" : "string"
                } ]
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "",
            "headers" : { },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/storevalidatedschema"
                },
                "example" : {
                  "event_code" : "r-shp-21",
                  "success" : true,
                  "version" : 3
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/get_observed_schema" : {
      "get" : {
        "tags" : [ "Misc" ],
        "summary" : "get observed schema",
        "operationId" : "getobservedschema",
        "parameters" : [ {
          "name" : "event_code",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "r-shp-21"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "headers" : { },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/getobservedschema"
                },
                "example" : {
                  "observed_schema" : {
                    "end_date" : "2020-01-09",
                    "event_code" : "r-shp-21",
                    "event_metadata" : [ {
                      "field_name" : "event_name",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "types" : [ "string" ],
                      "values" : [ "exams names & icons" ]
                    }, {
                      "field_name" : "event_type",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "types" : [ "string" ],
                      "values" : [ "click" ]
                    }, {
                      "field_name" : "log_type",
                      "is_null_allowed" : false,
                      "is_optional" : true,
                      "types" : [ "string" ],
                      "values" : [ "search-home-page", "search-result", "institute", "signup" ]
                    }, {
                      "field_name" : "nav_element",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "types" : [ "string" ],
                      "values" : [ "bottom exam bar" ]
                    } ],
                    "extra_params" : [ {
                      "field_name" : "exam_selected",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "types" : [ "string" ]
                    }, {
                      "field_name" : "user_query",
                      "is_null_allowed" : false,
                      "is_optional" : true,
                      "types" : [ "string" ]
                    } ],
                    "is_validated" : true,
                    "start_date" : "2019-01-01"
                  },
                  "success" : true
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/search_event_codes" : {
      "get" : {
        "tags" : [ "Misc" ],
        "summary" : "search event code",
        "operationId" : "searcheventcode",
        "parameters" : [ {
          "name" : "query",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "search"
          }
        }, {
          "name" : "schema_type",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "validated"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "headers" : { },
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/components/schemas/searcheventcode"
                  }
                },
                "example" : [ {
                  "event_code" : "r-shp-21",
                  "event_name" : "exams names & icons",
                  "event_type" : "click",
                  "log_type" : "search-home-page",
                  "nav_element" : "bottom exam bar"
                }, {
                  "event_code" : "r-shp-1",
                  "event_name" : "page load",
                  "event_type" : "page-load",
                  "log_type" : "search-home-page",
                  "nav_element" : ""
                }, {
                  "event_code" : "r-pw-86",
                  "event_name" : "page load",
                  "event_type" : "page-load",
                  "log_type" : "search-home-page",
                  "nav_element" : ""
                }, {
                  "event_code" : "r-shp-23",
                  "event_name" : "page load",
                  "event_type" : "page-load",
                  "log_type" : "search-home-page",
                  "nav_element" : ""
                } ]
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/stats" : {
      "get" : {
        "tags" : [ "Misc" ],
        "summary" : "stats",
        "operationId" : "stats",
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "",
            "headers" : { },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/stats"
                },
                "example" : {
                  "observed_event_codes" : 650,
                  "validated_event_codes" : 4
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    },
    "/get_validated_schema" : {
      "get" : {
        "tags" : [ "Misc" ],
        "summary" : "get validated schema",
        "operationId" : "getvalidatedschema",
        "parameters" : [ {
          "name" : "event_code",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "r-shp-1"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "",
            "headers" : { },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/getvalidatedschema"
                },
                "example" : {
                  "success" : true,
                  "validated_schema" : {
                    "email_id" : "karan.mountblue@embibe.com",
                    "event_code" : "r-shp-1",
                    "event_metadata" : [ {
                      "field_name" : "event_name",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "type" : "string",
                      "value" : "page load"
                    }, {
                      "field_name" : "event_type",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "type" : "string",
                      "value" : "page-load"
                    }, {
                      "field_name" : "log_type",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "type" : "string",
                      "value" : "search-home-page"
                    }, {
                      "field_name" : "nav_element",
                      "is_null_allowed" : false,
                      "is_optional" : false,
                      "type" : "string",
                      "value" : ""
                    } ],
                    "extra_params" : [ ],
                    "time_of_update" : 1580127496552,
                    "version" : 6
                  }
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    }
  },
  "components" : {
    "schemas" : {
      "storevalidatedschemarequest" : {
        "title" : "storevalidatedschemarequest",
        "required" : [ "event_code", "event_metadata", "extra_params" ],
        "type" : "object",
        "properties" : {
          "event_code" : {
            "type" : "string"
          },
          "event_metadata" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/EventMetadatum"
            }
          },
          "extra_params" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ExtraParam"
            }
          }
        },
        "example" : {
          "event_code" : "r-shp-21",
          "event_metadata" : [ {
            "field_name" : "event_name",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : "exams names & icons"
          }, {
            "field_name" : "event_type",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : "click"
          }, {
            "field_name" : "log_type",
            "is_null_allowed" : false,
            "is_optional" : true,
            "type" : "string",
            "value" : "search-home-page"
          }, {
            "field_name" : "nav_element",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : "bottom exam bar"
          } ],
          "extra_params" : [ {
            "field_name" : "exam_selected",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string"
          }, {
            "field_name" : "user_query",
            "is_null_allowed" : false,
            "is_optional" : true,
            "type" : "string"
          } ]
        }
      },
      "EventMetadatum" : {
        "title" : "EventMetadatum",
        "required" : [ "field_name", "is_null_allowed", "is_optional", "type", "value" ],
        "type" : "object",
        "properties" : {
          "field_name" : {
            "type" : "string"
          },
          "is_null_allowed" : {
            "type" : "boolean"
          },
          "is_optional" : {
            "type" : "boolean"
          },
          "type" : {
            "type" : "string"
          },
          "value" : {
            "type" : "string"
          }
        },
        "example" : {
          "field_name" : "event_name",
          "is_null_allowed" : false,
          "is_optional" : false,
          "type" : "string",
          "value" : "exams names & icons"
        }
      },
      "ExtraParam" : {
        "title" : "ExtraParam",
        "required" : [ "field_name", "is_null_allowed", "is_optional", "type" ],
        "type" : "object",
        "properties" : {
          "field_name" : {
            "type" : "string"
          },
          "is_null_allowed" : {
            "type" : "boolean"
          },
          "is_optional" : {
            "type" : "boolean"
          },
          "type" : {
            "type" : "string"
          }
        },
        "example" : {
          "field_name" : "exam_selected",
          "is_null_allowed" : false,
          "is_optional" : false,
          "type" : "string"
        }
      },
      "storevalidatedschema" : {
        "title" : "storevalidatedschema",
        "required" : [ "event_code", "success", "version" ],
        "type" : "object",
        "properties" : {
          "event_code" : {
            "type" : "string"
          },
          "success" : {
            "type" : "boolean"
          },
          "version" : {
            "type" : "integer",
            "format" : "int32"
          }
        },
        "example" : {
          "event_code" : "r-shp-21",
          "success" : true,
          "version" : 3
        }
      },
      "getobservedschema" : {
        "title" : "getobservedschema",
        "required" : [ "observed_schema", "success" ],
        "type" : "object",
        "properties" : {
          "observed_schema" : {
            "$ref" : "#/components/schemas/ObservedSchema"
          },
          "success" : {
            "type" : "boolean"
          }
        },
        "example" : {
          "observed_schema" : {
            "end_date" : "2020-01-09",
            "event_code" : "r-shp-21",
            "event_metadata" : [ {
              "field_name" : "event_name",
              "is_null_allowed" : false,
              "is_optional" : false,
              "types" : [ "string" ],
              "values" : [ "exams names & icons" ]
            }, {
              "field_name" : "event_type",
              "is_null_allowed" : false,
              "is_optional" : false,
              "types" : [ "string" ],
              "values" : [ "click" ]
            }, {
              "field_name" : "log_type",
              "is_null_allowed" : false,
              "is_optional" : true,
              "types" : [ "string" ],
              "values" : [ "search-home-page", "search-result", "institute", "signup" ]
            }, {
              "field_name" : "nav_element",
              "is_null_allowed" : false,
              "is_optional" : false,
              "types" : [ "string" ],
              "values" : [ "bottom exam bar" ]
            } ],
            "extra_params" : [ {
              "field_name" : "exam_selected",
              "is_null_allowed" : false,
              "is_optional" : false,
              "types" : [ "string" ]
            }, {
              "field_name" : "user_query",
              "is_null_allowed" : false,
              "is_optional" : true,
              "types" : [ "string" ]
            } ],
            "is_validated" : true,
            "start_date" : "2019-01-01"
          },
          "success" : true
        }
      },
      "ObservedSchema" : {
        "title" : "ObservedSchema",
        "required" : [ "end_date", "event_code", "event_metadata", "extra_params", "is_validated", "start_date" ],
        "type" : "object",
        "properties" : {
          "end_date" : {
            "type" : "string"
          },
          "event_code" : {
            "type" : "string"
          },
          "event_metadata" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/EventMetadatum1"
            }
          },
          "extra_params" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/ExtraParam1"
            }
          },
          "is_validated" : {
            "type" : "boolean"
          },
          "start_date" : {
            "type" : "string"
          }
        },
        "example" : {
          "end_date" : "2020-01-09",
          "event_code" : "r-shp-21",
          "event_metadata" : [ {
            "field_name" : "event_name",
            "is_null_allowed" : false,
            "is_optional" : false,
            "types" : [ "string" ],
            "values" : [ "exams names & icons" ]
          }, {
            "field_name" : "event_type",
            "is_null_allowed" : false,
            "is_optional" : false,
            "types" : [ "string" ],
            "values" : [ "click" ]
          }, {
            "field_name" : "log_type",
            "is_null_allowed" : false,
            "is_optional" : true,
            "types" : [ "string" ],
            "values" : [ "search-home-page", "search-result", "institute", "signup" ]
          }, {
            "field_name" : "nav_element",
            "is_null_allowed" : false,
            "is_optional" : false,
            "types" : [ "string" ],
            "values" : [ "bottom exam bar" ]
          } ],
          "extra_params" : [ {
            "field_name" : "exam_selected",
            "is_null_allowed" : false,
            "is_optional" : false,
            "types" : [ "string" ]
          }, {
            "field_name" : "user_query",
            "is_null_allowed" : false,
            "is_optional" : true,
            "types" : [ "string" ]
          } ],
          "is_validated" : true,
          "start_date" : "2019-01-01"
        }
      },
      "EventMetadatum1" : {
        "title" : "EventMetadatum1",
        "required" : [ "field_name", "is_null_allowed", "is_optional", "types", "values" ],
        "type" : "object",
        "properties" : {
          "field_name" : {
            "type" : "string"
          },
          "is_null_allowed" : {
            "type" : "boolean"
          },
          "is_optional" : {
            "type" : "boolean"
          },
          "types" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "values" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        },
        "example" : {
          "field_name" : "event_name",
          "is_null_allowed" : false,
          "is_optional" : false,
          "types" : [ "string" ],
          "values" : [ "exams names & icons" ]
        }
      },
      "ExtraParam1" : {
        "title" : "ExtraParam1",
        "required" : [ "field_name", "is_null_allowed", "is_optional", "types" ],
        "type" : "object",
        "properties" : {
          "field_name" : {
            "type" : "string"
          },
          "is_null_allowed" : {
            "type" : "boolean"
          },
          "is_optional" : {
            "type" : "boolean"
          },
          "types" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        },
        "example" : {
          "field_name" : "exam_selected",
          "is_null_allowed" : false,
          "is_optional" : false,
          "types" : [ "string" ]
        }
      },
      "searcheventcode" : {
        "title" : "searcheventcode",
        "required" : [ "event_code", "event_name", "event_type", "log_type", "nav_element" ],
        "type" : "object",
        "properties" : {
          "event_code" : {
            "type" : "string"
          },
          "event_name" : {
            "type" : "string"
          },
          "event_type" : {
            "type" : "string"
          },
          "log_type" : {
            "type" : "string"
          },
          "nav_element" : {
            "type" : "string"
          }
        },
        "example" : {
          "event_code" : "r-shp-21",
          "event_name" : "exams names & icons",
          "event_type" : "click",
          "log_type" : "search-home-page",
          "nav_element" : "bottom exam bar"
        }
      },
      "stats" : {
        "title" : "stats",
        "required" : [ "observed_event_codes", "validated_event_codes" ],
        "type" : "object",
        "properties" : {
          "observed_event_codes" : {
            "type" : "integer",
            "format" : "int32"
          },
          "validated_event_codes" : {
            "type" : "integer",
            "format" : "int32"
          }
        },
        "example" : {
          "observed_event_codes" : 650,
          "validated_event_codes" : 4
        }
      },
      "getvalidatedschema" : {
        "title" : "getvalidatedschema",
        "required" : [ "success", "validated_schema" ],
        "type" : "object",
        "properties" : {
          "success" : {
            "type" : "boolean"
          },
          "validated_schema" : {
            "$ref" : "#/components/schemas/ValidatedSchema"
          }
        },
        "example" : {
          "success" : true,
          "validated_schema" : {
            "email_id" : "karan.mountblue@embibe.com",
            "event_code" : "r-shp-1",
            "event_metadata" : [ {
              "field_name" : "event_name",
              "is_null_allowed" : false,
              "is_optional" : false,
              "type" : "string",
              "value" : "page load"
            }, {
              "field_name" : "event_type",
              "is_null_allowed" : false,
              "is_optional" : false,
              "type" : "string",
              "value" : "page-load"
            }, {
              "field_name" : "log_type",
              "is_null_allowed" : false,
              "is_optional" : false,
              "type" : "string",
              "value" : "search-home-page"
            }, {
              "field_name" : "nav_element",
              "is_null_allowed" : false,
              "is_optional" : false,
              "type" : "string",
              "value" : ""
            } ],
            "extra_params" : [ ],
            "time_of_update" : 1580127496552,
            "version" : 6
          }
        }
      },
      "ValidatedSchema" : {
        "title" : "ValidatedSchema",
        "required" : [ "email_id", "event_code", "event_metadata", "extra_params", "time_of_update", "version" ],
        "type" : "object",
        "properties" : {
          "email_id" : {
            "type" : "string"
          },
          "event_code" : {
            "type" : "string"
          },
          "event_metadata" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/EventMetadatum"
            }
          },
          "extra_params" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "time_of_update" : {
            "type" : "integer",
            "format" : "int64"
          },
          "version" : {
            "type" : "integer",
            "format" : "int32"
          }
        },
        "example" : {
          "email_id" : "karan.mountblue@embibe.com",
          "event_code" : "r-shp-1",
          "event_metadata" : [ {
            "field_name" : "event_name",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : "page load"
          }, {
            "field_name" : "event_type",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : "page-load"
          }, {
            "field_name" : "log_type",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : "search-home-page"
          }, {
            "field_name" : "nav_element",
            "is_null_allowed" : false,
            "is_optional" : false,
            "type" : "string",
            "value" : ""
          } ],
          "extra_params" : [ ],
          "time_of_update" : 1580127496552,
          "version" : 6
        }
      }
    },
    "securitySchemes" : {
      "httpBearer" : {
        "type" : "http",
        "scheme" : "bearer"
      }
    }
  },
  "security" : [ {
    "httpBearer" : [ ]
  } ],
  "tags" : [ {
    "name" : "Misc",
    "description" : ""
  } ]
}