openapi: 3.0.2
info:
  title: ServiceAAA
  version: "1.0.0-oas3"
servers:
  - url: 'http://localhost:3000/v1'
    description: ''
paths:
  /product:
    get:
      tags:
        - Product
      parameters:
        - name: id
          description: ''
          schema:
            type: string
          in: query
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseProduct'
              examples:
                Success:
                  value:
                    Email: some text
                    CompGroupId: 29
                    IsActive: true
                    companyName: some text
                    localCurrency: some text
                    Name: some text
                    IsAD: true
                    paymentType:
                      - id: 46
                        paymentType: some text
                        compCode: some text
                        requestTypeId: 47
                      - id: 45
                        paymentType: some text
                        compCode: some text
                        requestTypeId: 67
                    PositionEN: some text
                    HolidayGroup: 6
                    BU: some text
                    Currency:
                      - currency: some text
                        decimal: 76
                      - currency: some text
                        decimal: 45
                    ShiftDate: 28
                    UserName: some text
                    Position: some text
                    AccountNo: some text
                    LocationId: 77
                    DOACurrency: some text
                    Title: some text
                    CreateUser: some text
                    TitleEN: some text
                    CompCode: some text
                    companyNameEN: some text
                    IsQRCode: true
                    IsEmployee: true
                    ManagerUserId: some text
                    UserId: some text
                    NameEN: some text
                    Country: some text
                    GetRequest: some text
                    SurnameEN: some text
                    UpdateUser: some text
                    location:
                      - locationId: 15
                        location: some text
                        paymentChannel: some text
                        pettyCashLimit: 90
                        companyCode: some text
                      - locationId: 17
                        location: some text
                        paymentChannel: some text
                        pettyCashLimit: 71
                        companyCode: some text
          description: success
      summary: get product
    post:
      requestBody:
        description: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestBodyCreateProduct'
            examples:
              body:
                value:
                  id: aa
        required: true
      tags:
        - Product
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseProduct'
              examples:
                Success:
                  value:
                    Email: some text
                    CompGroupId: 29
                    IsActive: true
                    companyName: some text
                    localCurrency: some text
                    Name: some text
                    IsAD: true
                    paymentType:
                      - id: 46
                        paymentType: some text
                        compCode: some text
                        requestTypeId: 47
                      - id: 45
                        paymentType: some text
                        compCode: some text
                        requestTypeId: 67
                    PositionEN: some text
                    HolidayGroup: 6
                    BU: some text
                    Currency:
                      - currency: some text
                        decimal: 76
                      - currency: some text
                        decimal: 45
                    ShiftDate: 28
                    UserName: some text
                    Position: some text
                    AccountNo: some text
                    LocationId: 77
                    DOACurrency: some text
                    Title: some text
                    CreateUser: some text
                    TitleEN: some text
                    CompCode: some text
                    companyNameEN: some text
                    IsQRCode: true
                    IsEmployee: true
                    ManagerUserId: some text
                    UserId: some text
                    NameEN: some text
                    Country: some text
                    GetRequest: some text
                    SurnameEN: some text
                    UpdateUser: some text
                    location:
                      - locationId: 15
                        location: some text
                        paymentChannel: some text
                        pettyCashLimit: 90
                        companyCode: some text
                      - locationId: 17
                        location: some text
                        paymentChannel: some text
                        pettyCashLimit: 71
                        companyCode: some text
          description: success
      summary: Create product
components:
  schemas:
    responseProduct:
      title: Root Type for responseProduct
      description: ''
      type: object
      properties:
        Email:
          type: string
        CompGroupId:
          format: int32
          type: integer
        IsActive:
          type: boolean
        companyName:
          type: string
        localCurrency:
          type: string
        Name:
          type: string
        IsAD:
          type: boolean
        paymentType:
          type: array
          items:
            type: object
            properties:
              id:
                format: int32
                type: integer
              paymentType:
                type: string
              compCode:
                type: string
              requestTypeId:
                format: int32
                type: integer
        PositionEN:
          type: string
        HolidayGroup:
          format: int32
          type: integer
        BU:
          type: string
        Currency:
          type: array
          items:
            type: object
            properties:
              currency:
                type: string
              decimal:
                format: int32
                type: integer
        ShiftDate:
          format: int32
          type: integer
        UserName:
          type: string
        Position:
          type: string
        AccountNo:
          type: string
        LocationId:
          format: int32
          type: integer
        DOACurrency:
          type: string
        Title:
          type: string
        CreateUser:
          type: string
        TitleEN:
          type: string
        CompCode:
          type: string
        companyNameEN:
          type: string
        IsQRCode:
          type: boolean
        IsEmployee:
          type: boolean
        ManagerUserId:
          type: string
        UserId:
          type: string
        NameEN:
          type: string
        Country:
          type: string
        GetRequest:
          type: string
        SurnameEN:
          type: string
        UpdateUser:
          type: string
        location:
          type: array
          items:
            type: object
            properties:
              locationId:
                format: int32
                type: integer
              location:
                type: string
              paymentChannel:
                type: string
              pettyCashLimit:
                format: int32
                type: integer
              companyCode:
                type: string
      example:
        Email: some text
        CompGroupId: 29
        IsActive: true
        companyName: some text
        localCurrency: some text
        Name: some text
        IsAD: true
        paymentType:
          - id: 46
            paymentType: some text
            compCode: some text
            requestTypeId: 47
          - id: 45
            paymentType: some text
            compCode: some text
            requestTypeId: 67
        PositionEN: some text
        HolidayGroup: 6
        BU: some text
        Currency:
          - currency: some text
            decimal: 76
          - currency: some text
            decimal: 45
        ShiftDate: 28
        UserName: some text
        Position: some text
        AccountNo: some text
        LocationId: 77
        DOACurrency: some text
        Title: some text
        CreateUser: some text
        TitleEN: some text
        CompCode: some text
        companyNameEN: some text
        IsQRCode: true
        IsEmployee: true
        ManagerUserId: some text
        UserId: some text
        NameEN: some text
        Country: some text
        GetRequest: some text
        SurnameEN: some text
        UpdateUser: some text
        location:
          - locationId: 15
            location: some text
            paymentChannel: some text
            pettyCashLimit: 90
            companyCode: some text
          - locationId: 17
            location: some text
            paymentChannel: some text
            pettyCashLimit: 71
            companyCode: some text
    requestBodyCreateProduct:
      title: Root Type for requestBodyCreateProduct
      description: ''
      type: object
      properties:
        id:
          type: string
      example:
        id: aa
