openapi: 3.0.0
info:
  title: Online Store
  contact: {}
  version: "1.0.0-oas3"
servers:
  - url: 'http://127.0.0.1:8000/api'
    variables: {}
paths:
  /register:
    post:
      tags:
        - Misc
      summary: register user
      operationId: registeruser
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
                - name
                - email
                - password
              type: object
              properties:
                name:
                  type: string
                  example: nada
                email:
                  type: string
                  example: nadaa@gmail.com
                password:
                  type: integer
                  format: int32
                  example: 123456
        required: false
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 13:03:04 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '59'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registeruser'
              example:
                data:
                  user:
                    name: nada
                    email: nadaaa@gmail.com
                    updated_at: '2020-04-16T13:03:04Z'
                    created_at: '2020-04-16T13:03:04Z'
                    id: 4
                  token: >-
                    RiBRAoyWwI117vQU8j0QKZ3lGtVhSxBXyuKulpxf9atmmTIq1TCMbE1IbVJuuGbasxDvWi1GjBnV5dcM
                errors: null
                code: 201
                msg: User registered successfully
      deprecated: false
  /login:
    post:
      tags:
        - Misc
      summary: login user
      operationId: loginuser
      parameters:
        - name: Content-Type
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
                - email
                - password
              type: object
              properties:
                email:
                  type: string
                  example: nadaa@gmail.com
                password:
                  type: integer
                  format: int32
                  example: 123456
        required: false
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:31:41 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '59'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginuser'
              example:
                data:
                  token: >-
                    DQ1joyhXtlfBVJcahePK5sIhbD4LJC6oM76AbTAbutO4CpeohUw3cFVvTjwsd3IdwfBfa5zxai77xO4l
                errors: null
                code: 200
                msg: User logged in successfully
        '401':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginuser1'
              example:
                data: null
                errors:
                  errors: UnAuthorised
                code: 401
                msg: incorrect credentials
      deprecated: false
  /products:
    get:
      tags:
        - Misc
      summary: list products
      operationId: listproducts
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:32:18 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '58'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listproducts'
              example:
                data:
                  - name: product2
                    price: 11
                    image: null
                  - name: product1
                    price: 11
                    image: null
                errors: null
                code: 200
                msg: Listing successfully
      deprecated: false
  /featured_products:
    get:
      tags:
        - Misc
      summary: list featured products
      operationId: listfeaturedproducts
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:32:35 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '57'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listfeaturedproducts'
              example:
                data:
                  - name: product2
                    price: 11
                    image: null
                errors: null
                code: 200
                msg: Listing successfully
      deprecated: false
  /products_category/2:
    get:
      tags:
        - Misc
      summary: list products in a category
      operationId: listproductsinacategory
      parameters: []
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:32:48 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '59'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listproductsinacategory1'
              example:
                data:
                  - name: product2
                    price: 11
                    image: null
                  - name: product1
                    price: 11
                    image: null
                errors: null
                code: 200
                msg: Listing successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getcategory1'
              example:
                data: null
                errors: null
                code: 404
                msg: No found products
      deprecated: false
  /categories:
    get:
      tags:
        - Misc
      summary: list categories
      operationId: listcategories
      parameters: []
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:33:33 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '58'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listcategories'
              example:
                data:
                  - name: nadaaa
                    details: wwwwwwwwwwwwwwwwww
                    image: null
                  - name: category2
                    details: dddddddddddddddd
                    image: 24-hours.svg
                errors: null
                code: 200
                msg: Listing successfully
      deprecated: false
  /products/1:
    get:
      tags:
        - Misc
      summary: get product
      operationId: getproduct
      parameters: []
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:34:02 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '57'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getproduct1'
              example:
                data:
                  id: 1
                  name: product2
                  price: 11
                  code: 2
                  image: null
                  category_id: 2
                  created_at: '2020-04-15T14:59:15Z'
                  updated_at: '2020-04-15T14:59:15Z'
                  featured: 1
                errors: null
                code: 200
                msg: Product Found
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getcategory1'
              example:
                data: null
                errors: null
                code: 404
                msg: Product not found
      deprecated: false
  /categories/1:
    get:
      tags:
        - Misc
      summary: get category
      operationId: getcategory
      parameters: []
      responses:
        '200':
          description: ''
          headers:
            Host:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '127.0.0.1:8000'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'Thu, 16 Apr 2020 12:34:12 GMT'
            Connection:
              content:
                text/plain:
                  schema:
                    type: string
                  example: close
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: PHP/7.2.27
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 'no-cache, private'
            X-RateLimit-Limit:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '60'
            X-RateLimit-Remaining:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '56'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getcategory'
              example:
                data:
                  id: 1
                  name: nadaaa
                  details: wwwwwwwwwwwwwwwwww
                  image: null
                  created_at: '2020-04-15T12:28:57Z'
                  updated_at: '2020-04-15T12:28:57Z'
                errors: null
                code: 200
                msg: Category Found
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getcategory1'
              example:
                data: null
                errors: null
                code: 404
                msg: Category not found
      deprecated: false
components:
  schemas:
    registeruser:
      title: registeruser
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Data'
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          user:
            name: nada
            email: nadaaa@gmail.com
            updated_at: '2020-04-16T13:03:04Z'
            created_at: '2020-04-16T13:03:04Z'
            id: 4
          token: >-
            RiBRAoyWwI117vQU8j0QKZ3lGtVhSxBXyuKulpxf9atmmTIq1TCMbE1IbVJuuGbasxDvWi1GjBnV5dcM
        errors: null
        code: 201
        msg: User registered successfully
    Data:
      title: Data
      required:
        - user
        - token
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string
      example:
        user:
          name: nada
          email: nadaaa@gmail.com
          updated_at: '2020-04-16T13:03:04Z'
          created_at: '2020-04-16T13:03:04Z'
          id: 4
        token: >-
          RiBRAoyWwI117vQU8j0QKZ3lGtVhSxBXyuKulpxf9atmmTIq1TCMbE1IbVJuuGbasxDvWi1GjBnV5dcM
    User:
      title: User
      required:
        - name
        - email
        - updated_at
        - created_at
        - id
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        updated_at:
          type: string
        created_at:
          type: string
        id:
          type: integer
          format: int32
      example:
        name: nada
        email: nadaaa@gmail.com
        updated_at: '2020-04-16T13:03:04Z'
        created_at: '2020-04-16T13:03:04Z'
        id: 4
    loginuser:
      title: loginuser
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Data1'
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          token: >-
            DQ1joyhXtlfBVJcahePK5sIhbD4LJC6oM76AbTAbutO4CpeohUw3cFVvTjwsd3IdwfBfa5zxai77xO4l
        errors: null
        code: 200
        msg: User logged in successfully
    Data1:
      title: Data1
      required:
        - token
      type: object
      properties:
        token:
          type: string
      example:
        token: >-
          DQ1joyhXtlfBVJcahePK5sIhbD4LJC6oM76AbTAbutO4CpeohUw3cFVvTjwsd3IdwfBfa5zxai77xO4l
    loginuser1:
      title: loginuser1
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          type: string
          nullable: true
        errors:
          $ref: '#/components/schemas/Errors'
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data: null
        errors:
          errors: UnAuthorised
        code: 401
        msg: incorrect credentials
    Errors:
      title: Errors
      required:
        - errors
      type: object
      properties:
        errors:
          type: string
      example:
        errors: UnAuthorised
    listproducts:
      title: listproducts
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data2'
          description: ''
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          - name: product2
            price: 11
            image: null
          - name: product1
            price: 11
            image: null
        errors: null
        code: 200
        msg: Listing successfully
    Data2:
      title: Data2
      required:
        - name
        - price
        - image
      type: object
      properties:
        name:
          type: string
        price:
          type: integer
          format: int32
        image:
          type: string
          nullable: true
      example:
        name: product2
        price: 11
        image: null
    listfeaturedproducts:
      title: listfeaturedproducts
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data2'
          description: ''
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          - name: product2
            price: 11
            image: null
        errors: null
        code: 200
        msg: Listing successfully
    listproductsinacategory1:
      title: listproductsinacategory1
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data2'
          description: ''
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          - name: product2
            price: 11
            image: null
          - name: product1
            price: 11
            image: null
        errors: null
        code: 200
        msg: Listing successfully
    listcategories:
      title: listcategories
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data5'
          description: ''
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          - name: nadaaa
            details: wwwwwwwwwwwwwwwwww
            image: null
          - name: category2
            details: dddddddddddddddd
            image: 24-hours.svg
        errors: null
        code: 200
        msg: Listing successfully
    Data5:
      title: Data5
      required:
        - name
        - details
        - image
      type: object
      properties:
        name:
          type: string
        details:
          type: string
        image:
          type: string
          nullable: true
      example:
        name: nadaaa
        details: wwwwwwwwwwwwwwwwww
        image: null
    getproduct1:
      title: getproduct1
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Data6'
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          id: 1
          name: product2
          price: 11
          code: 2
          image: null
          category_id: 2
          created_at: '2020-04-15T14:59:15Z'
          updated_at: '2020-04-15T14:59:15Z'
          featured: 1
        errors: null
        code: 200
        msg: Product Found
    Data6:
      title: Data6
      required:
        - id
        - name
        - price
        - code
        - image
        - category_id
        - created_at
        - updated_at
        - featured
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        price:
          type: integer
          format: int32
        code:
          type: integer
          format: int32
        image:
          type: string
          nullable: true
        category_id:
          type: integer
          format: int32
        created_at:
          type: string
        updated_at:
          type: string
        featured:
          type: integer
          format: int32
      example:
        id: 1
        name: product2
        price: 11
        code: 2
        image: null
        category_id: 2
        created_at: '2020-04-15T14:59:15Z'
        updated_at: '2020-04-15T14:59:15Z'
        featured: 1
    getcategory:
      title: getcategory
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Data7'
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data:
          id: 1
          name: nadaaa
          details: wwwwwwwwwwwwwwwwww
          image: null
          created_at: '2020-04-15T12:28:57Z'
          updated_at: '2020-04-15T12:28:57Z'
        errors: null
        code: 200
        msg: Category Found
    Data7:
      title: Data7
      required:
        - id
        - name
        - details
        - image
        - created_at
        - updated_at
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        details:
          type: string
        image:
          type: string
          nullable: true
        created_at:
          type: string
        updated_at:
          type: string
      example:
        id: 1
        name: nadaaa
        details: wwwwwwwwwwwwwwwwww
        image: null
        created_at: '2020-04-15T12:28:57Z'
        updated_at: '2020-04-15T12:28:57Z'
    getcategory1:
      title: getcategory1
      required:
        - data
        - errors
        - code
        - msg
      type: object
      properties:
        data:
          type: string
          nullable: true
        errors:
          type: string
          nullable: true
        code:
          type: integer
          format: int32
        msg:
          type: string
      example:
        data: null
        errors: null
        code: 404
        msg: Category not found
tags:
  - name: Misc
    description: ''