openapi: 3.0.0
servers: []
info:
  description: 'This Interface Agreement document covers the API specification design for Physical Resource Fulfillment in Telkomsel'
  version: "1.3.0"
  title: Physical Resources Fulfillment
  termsOfService: 'http://api.telkomsel.com/terms/'
  contact:
    email: IT-SolArch-L@telkomsel.co.id
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags: []
paths:
  /physical-resource-fulfillment/orders:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    post:
      security:
        - basicAuth: []
      operationId: create-new-physical-products-order
      description: API to create new physical resources fullfilment order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_prf_request'
      responses:
        '200':
          $ref: '#/components/responses/prfResponseSuccess'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
    get:
      operationId: list-physical-resources-fulfillment-order
      description: This service is to retrieve list of physical resources order assigned to a TDC PIC. By default, the list sorted by created date of the orders in descending order
      parameters:
        - name: tdc_id
          in: query
          required: false
          description: TDC ID that used when retrieving list of physical products orders assigned respectively.
          schema:
            type: integer
            example: 1100
        - name: from
          in: query
          required: true
          description: Offset of the list that will be fetched for a page. Start index is from 1. Page n will have value from=size+(n-1), n>=2 
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          description: Size per page. Default value is 20 records per page  
          schema:
            type: integer
            example: 20
        - name: prf_type_id
          in: query
          required: false
          description: ID of the physical resources type. List of ID type can be retrieved from API "GET /physical-resource-fulfillment/types". For `sim-card` starter pack pass value ID=0
          schema:
            type: integer
            example: '0'
        - name: prf_subtype_id
          in: query
          required: false
          description: ID of the physical resources subtype. List of ID type can be retrieved from API "GET /physical-resource-fulfillment/types". For `sim-card`\`prepaid` starter pack pass value ID=1
          schema:
            type: integer
            example: 1
        - name: status
          in: query
          required: false
          description: Filter option to only display order for a given status only  
          schema:
            type: string
            enum:
              - OPEN
              - ON_DELIVERY
              - COMPLETED
              - CANCELLED
              - FAILED
            example: OPEN
        - name: created_at
          in: query
          required: false
          description: Filter option to only display order for a given period of order created date 
          schema:
            type: string
            format: date
            example: '2020-03-29'
        - name: shipping_date
          in: query
          required: false
          description: Filter option to only display order for a given period of order shipping date  
          schema:
            type: string
            format: date
            example: '2020-03-29'
        - name: shipping_arrival_date
          in: query
          required: false
          description: Filter option to only display order for a given period of order received by customers  
          schema:
            type: string
            format: date
            example: '2020-03-29'
        - name: channel_transaction_id
          in: query
          required: false
          description: Filter option to only display order for a given transaction ID
          schema:
            type: string
            example: 'MYTSEL123456789'
        - name: msisdn_requestor
          in: query
          required: false
          description: Filter option to only display order for a given MSISDN that create the PRF request
          schema:
            type: string
            example: '6281212345678'
        - name: sort
          in: query
          required: false
          description: Sort option to display the list. Available values are   created_at and status. Accommodate complex sorting requirements by letting the sort parameter take in list of comma separated fields, each with a possible unary negative to imply descending sort order
          schema:
            type: string
            example: '-status,created_at'
      responses:
        '200':
          description: "Success retrieving list of physical resources fulfillment request order"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/list_prf_response'  
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /physical-resource-fulfillment/orders/{prfOrderId}:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
      - name: prfOrderId
        in: path
        required: true
        description: ID of the physical resources fulfillment order request
        schema:
          type: string
          example: 'c1b9c176-37dd-45d9-8587-7964980119dc'
    patch:
      operationId: update-physical-fulfillment-order-status
      description: |
        API to update existing Physical Resource Fulfillment request (assignment and status). Resource Fulfillment status can only be updated if the fulfillment request status follows valid transition state for public API. 
        1. `OPEN` to `CANCELLED` - if there is request cancellation from customer; performed by CTP via DSC (DSC - ESB - PRF)
        2. `ON_DELIVERY` to `CANCELLED` - valid if there is request cancellation from customer **AND** the order is out of SLA (`current date` - `created_at`) > 3x24 hours
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_prf_status_request'
            examples:
              OPEN to CANCELLED:
                value:
                  tdc_id: 1500
                  order_state: "CANCELLED"
                  order_notes: 'Cancelled by customer. Want to change recipient address'
              ON_DELIVERY to CANCELLED:
                value:
                  tdc_id: 1500
                  shipping_arrival_date: '2020-04-01'
                  order_state: 'CANCELLED'
                  order_notes: 'Order di cancel oleh customer'
      responses:
        '200':
          $ref: '#/components/responses/prfResponseSuccess'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /physical-resource-fulfillment/shippings/options:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    get:
      operationId: get-available-shipping-options
      description: API to retrieve all available shipping options
      parameters:
        - name: from
          in: query
          required: true
          description: Offset of the list that will be fetched for a page. Start index is from 1. Page n will have value from=size+(n-1), n>=2 
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          description: Size per page. Default value is 20 records per page  
          schema:
            type: integer
            example: 20
        - name: sort
          in: query
          required: false
          description: Sort option to display the list. Available values are `name`. Accommodate complex sorting requirements by letting the sort parameter take in list of comma separated fields, each with a possible unary negative to imply descending sort order
          schema:
            type: string
            example: '-name'
      responses:
        '200':
          description: "Success retrieving list of shipping options"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/list_shipping_options_response'  
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'        
  /physical-resource-fulfillment/shippings/tdc:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    get:
      operationId: get-tdc-pic
      description: 'API to get TDC PIC by various parameters : msisdn, kelurahan'
      parameters:
        - name: msisdn
          in: query
          required: false
          description: MSISDN of the TDC PIC
          schema:
            type: string
            example: '6281212345678'
        - name: kelurahan
          in: query
          required: false
          description: Kelurahan Name of TDC
          schema:
            type: string
            example: 'Babakan'
      responses:
        '200':
          description: "Success validating TDC PICs"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/valid_tdc_response'  
              examples:
                TDC is Active:
                    value:
                        data:
                          tdc_pic:
                            id: 11000
                            name: "Agus Sudrajat"
                            msisdn: "081312345678"
                            description : "TDC PIC untuk daerah Kelurahan Babakan"
                            cluster: "Kelurahan Babakan"
                            is_active: 1
                        meta:
                          took : 230,
                          status_code: 200
                          status_desc: "ok"
                TDC is Not Active (Out of stock):
                    value:
                        data:
                          tdc_pic:
                            id: 11000
                            name: "Agus Simo"
                            msisdn: "08138888888"
                            description : "TDC PIC untuk daerah Kelurahan Bakti Jaya"
                            cluster: "Bakti Jaya"
                            is_active: 0
                        meta:
                          took : 230,
                          status_code: 200
                          status_desc: "ok"
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /physical_resources_fulfillment/resources/types:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    get:
      operationId: list-available-physical-resources-type
      description: This service is to retrieve list of available physical resources type in PRF.
      parameters:
        - name: from
          in: query
          required: true
          description: Offset of the list that will be fetched for a page. Start index is from 1. Page n will have value from=size+(n-1), n>=2 
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          description: Size per page. Default value is 20 records per page  
          schema:
            type: integer
            example: 20
        - name: sort
          in: query
          required: false
          description: Sort option to display the list. Available values are type. Accommodate complex sorting requirements by letting the sort parameter take in list of comma separated fields, each with a possible unary negative to imply descending sort order
          schema:
            type: string
            example: '-type'
      responses:
        '200':
          description: "Success retrieving list of physical products order"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/list_prf_type_response'  
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /_exclusive/physical-resource-fulfillment/login:  
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    post:
      operationId: exclusive-login-tdc-pic
      description: 'API to validate TDC PIC login information'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_request'
      responses:
        '200':
          description: "TDC PIC authenticated"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/login_response'  
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /_exclusive/physical-resource-fulfillment/logout:  
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    post:
      security:
        - jwtAuth: []
      operationId: exclusive-logout-tdc-pic
      description: 'API to validate TDC PIC login information'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/logout_request'
      responses:
        '200':
          description: "TDC PIC authenticated"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/login_response'  
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /_exclusive/physical-resource-fulfillment/orders:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
    get:
      security:
        - jwtAuth: []
      operationId: exclusive-list-physical-resources-fulfillment-order
      description: This service is to retrieve list of physical resources order assigned to a TDC PIC. By default, the list sorted by created date of the orders in descending order
      parameters:
        - name: tdc_id
          in: query
          required: false
          description: TDC ID that used when retrieving list of physical products orders assigned respectively.
          schema:
            type: integer
            example: 1100
        - name: from
          in: query
          required: true
          description: Offset of the list that will be fetched for a page. Start index is from 1. Page n will have value from=size+(n-1), n>=2 
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          description: Size per page. Default value is 20 records per page  
          schema:
            type: integer
            example: 20
        - name: prf_type_id
          in: query
          required: false
          description: ID of the physical resources type. List of ID type can be retrieved from API "GET /physical-resource-fulfillment/types". For `sim-card` starter pack pass value ID=0
          schema:
            type: integer
            example: '0'
        - name: prf_subtype_id
          in: query
          required: false
          description: ID of the physical resources subtype. List of ID type can be retrieved from API "GET /physical-resource-fulfillment/types". For `sim-card`\`prepaid` starter pack pass value ID=1
          schema:
            type: integer
            example: 1
        - name: status
          in: query
          required: false
          description: Filter option to only display order for a given status only  
          schema:
            type: string
            enum:
              - OPEN
              - PROCESSED
              - ON_DELIVERY
              - COMPLETED
              - CANCELLED
              - FAILED
            example: OPEN
        - name: created_at
          in: query
          required: false
          description: Filter option to only display order for a given period of order created date 
          schema:
            type: string
            format: date
            example: '2020-03-29'
        - name: shipping_date
          in: query
          required: false
          description: Filter option to only display order for a given period of order shipping date  
          schema:
            type: string
            format: date
            example: '2020-03-29'
        - name: shipping_arrival_date
          in: query
          required: false
          description: Filter option to only display order for a given period of order received by customers  
          schema:
            type: string
            format: date
            example: '2020-03-29'
        - name: channel_transaction_id
          in: query
          required: false
          description: Filter option to only display order for a given transaction ID
          schema:
            type: string
            example: 'MYTSEL123456789'
        - name: msisdn_requestor
          in: query
          required: false
          description: Filter option to only display order for a given MSISDN that create the PRF request
          schema:
            type: string
            example: '6281212345678'
        - name: sort
          in: query
          required: false
          description: Sort option to display the list. Available values are   created_at and status. Accommodate complex sorting requirements by letting the sort parameter take in list of comma separated fields, each with a possible unary negative to imply descending sort order
          schema:
            type: string
            example: '-status,created_at'
      responses:
        '200':
          description: "Success retrieving list of physical resources fulfillment request order"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/list_prf_response'  
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /_exclusive/physical-resource-fulfillment/orders/{prfOrderId}:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
      - name: prfOrderId
        in: path
        required: true
        description: ID of the physical resources fulfillment order request
        schema:
          type: string
          example: 'c1b9c176-37dd-45d9-8587-7964980119dc'
    patch:
      security:
        - jwtAuth: []
      operationId: exclusive-update-physical-fulfillment-order-status
      description: |
        API to update existing Physical Resource Fulfillment request (assignment and status). Resource Fulfillment status can only be updated if the fulfillment request status follows valid transition state. 
        1. `OPEN` to `ON_DELIVERY` - change when TDC PIC assign to Direct Sales via Web Checkout Order UI
        2. `OPEN` to `CANCELLED` - if there is request cancellation from customer; performed by CTP via DSC (DSC - ESB - PRF)
        3. `ON_DELIVERY` to `COMPLETED` - if physical resources already delivered to destination customer; updated by TDC PIC via Web Checkout Order UI 
        4. `ON_DELIVERY` to `FAILED` - if physical resources cannot be delivered to destination customer e.g. customer is not at arrival address, customer cannot be contacted, etc.; updated by TDC PIC via Web Checkout Order UI
        5. `ON_DELIVERY` to `CANCELLED` - valid if there is request cancellation from customer **AND** the order is out of SLA (`current date` - `created_at`) > 3x24 hours
        
        Assignment to Direct Sales can only be done or updated to Direct Sales if status still in `OPEN` (Order Diterima)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_prf_status_request_exclusive'
            examples:
              OPEN to ON_DELIVERY:
                value:
                  ds_name: 'DC0001'
                  ds_msisdn: '6281287654321'
                  line_item_msisdn: '628127171717'
                  shipping_date: '2020-03-29'
                  order_state: "ON_DELIVERY"
              OPEN to CANCELLED:
                value:
                  order_state: "CANCELLED"
                  order_notes: 'Cancelled by customer. Want to change recipient address'
              ON_DELIVERY to COMPLETED:
                value:
                  shipping_arrival_date: '2020-04-01'
                  order_state: 'COMPLETED'
                  order_notes: ''
              ON_DELIVERY to CANCELLED:
                value:
                  shipping_arrival_date: '2020-04-01'
                  order_state: 'CANCELLED'
                  order_notes: 'Order di cancel oleh customer'
              ON_DELIVERY to FAILED:
                value:
                  shipping_arrival_date: '2020-04-01'
                  order_state: 'FAILED'
                  order_notes: 'Gagal diterima. Orang tidak ada dirumah'
      responses:
        '200':
          $ref: '#/components/responses/prfResponseSuccess'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalServerError'
    get:
      security:
        - jwtAuth: []
      parameters:
        - name: recipient_msisdn
          in: query
          description: MSISDN of the order’s recipient.
          required: false 
          schema:
            type: string
            example: '6281212345678'
        - name: requestor_msisdn
          in: query
          description: MSISDN of the order’s requestor. Mandatory if parameter recipient_msisdn is exists
          required: false
          schema:
            type: string
            example: '6281212345678'
      operationId: view-physical-products-order
      description: API to retrieve Physical Resource order details information
      responses:
        '200':
          description: "Success retrieving details info physical resources order"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/prf_detail_response'
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /_exclusive/physical-resource-fulfillment/performances/orders/{prfTypeId}/{prfSubTypeId}:
    parameters:
      - name: X-Request-ID
        in: header
        required: true
        description: Request id (can use UUID v4)
        schema:
          type: string
        example: "82422bd4-8751-41a4-9713-3dbab461fe88"
      - name: X-Channel-Id
        in: header
        required: true
        description: Channel Identifier 
        schema:
          type: string
        example: "TDWWEBAPI"
      - name: prfTypeId
        in: path
        required: true
        description: ID of the physical resources type. List of ID type can be retrieved from API "GET /physical-resource-fulfillment/types". For `sim-card` starter pack pass value ID=0
        schema:
          type: integer
          example: '0'
      - name: prfSubTypeId
        in: path
        required: true
        description: ID of the physical resources subtype. List of ID type can be retrieved from API "GET /physical-resource-fulfillment/types". For `sim-card` `prepaid` starter pack pass value ID=1
        schema:
          type: integer
          example: 1
    get:
      security:
        - jwtAuth: []
      operationId: exclusive-physical-resources-fulfillment-order-performance
      description: This service is to retrieve performance of PRF order within specified duration or period that aggregated based on daily, monthly, and yearly
      parameters:
        - name: created_at
          in: query
          required: false
          description: Filter option to only display order for a given period of order created date 
          schema:
            type: string
            format: date
            example: '2020-03-29'
      responses:
        '200':
          description: "Success retrieving physical resources fulfillment request order performance"
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/prf_report_response'  
              example:
                data:
                - aggregate_scope: daily
                  date_value: "29"
                  performance:
                    - order_state: "OPEN"
                      total : 2
                    - order_state: "ON_DELIVERY"
                      total: 10
                    - order_state: "COMPLETED"
                      total: 15
                    - order_state: "CANCELLED"
                      total: 0
                    - order_state: "FAILED"
                      total: 15
                - aggregate_scope: monthly
                  date_value: "3"
                  performance:
                    - order_state: "OPEN"
                      total : 30
                    - order_state: "ON_DELIVERY"
                      total: 20
                    - order_state: "COMPLETED"
                      total: 450
                    - order_state: "CANCELLED"
                      total: 2
                    - order_state: "FAILED"
                      total: 3
                - aggregate_scope: yearly
                  date_value: "2020"
                  performance:
                    - order_state: "OPEN"
                      total : 10
                    - order_state: "ON_DELIVERY"
                      total: 15
                    - order_state: "COMPLETED"
                      total: 3450
                    - order_state: "CANCELLED"
                      total: 10
                    - order_state: "FAILED"
                      total: 5
                meta:
                  took: 125
                  status_code: 200
                  status_desc: "success"
          headers:
            Content-Type:
              $ref: '#/components/headers/Content-Type'
            Content-Encoding:
              $ref: '#/components/headers/Content-Encoding'
        '400':
          $ref: '#/components/responses/InvalidRequest'
        '401': 
          $ref: '#/components/responses/UnauthorizedRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  headers:
    Content-Type:
      description: Content type of the response
      schema:
        type: string
        enum: 
        - "application/json"
    Content-Encoding:
      description: Content encoding used to transmit the response.
      schema:
        type: string
        enum: 
        - "gzip"
  responses:
    prfResponseSuccess:
      description: "Physical Resources fullfillment successfully processed"
      content:
        application/json: 
          schema:
            $ref: '#/components/schemas/update_prf_status_response'
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Content-Encoding:
          $ref: '#/components/headers/Content-Encoding'    
    InvalidRequest:
      description: "Invalid physical resources fulfillment order request"
      content:
        application/json: 
          schema:
            $ref: '#/components/schemas/meta_response'
          example:
            meta:
              took : 100
              status_code: 400
              status_desc: "invalid request params. <description of request param that invalid>"
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Content-Encoding:
          $ref: '#/components/headers/Content-Encoding'
    UnauthorizedRequest:
      description: "Not authorized"
      content:
        application/json: 
          schema:
            $ref: '#/components/schemas/meta_response'
          example:
            meta:
              took: 220
              status_code: 401
              status_desc: "Credentials is invalid / not authorized"
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Content-Encoding:
          $ref: '#/components/headers/Content-Encoding'
    InternalServerError:
      description: "Something went wrong in PRF when processing request"
      content:
        application/json: 
          schema:
            $ref: '#/components/schemas/meta_response'
          example:
            meta:
              took : 100
              status_code: 500
              status_desc: "Internal server error. Please try again"
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
        Content-Encoding:
          $ref: '#/components/headers/Content-Encoding'
    UnprocessableEntity:
      description: "PRF Request entity cannot be processed"
      content:
          application/json: 
            schema:
              $ref: '#/components/schemas/meta_response'
            example:
              meta:
                took : 100
                status_code: 422
                status_desc: "PRF Order cannot be updated violating valid transition state of the order"
      headers:
          Content-Type:
            $ref: '#/components/headers/Content-Type'
          Content-Encoding:
            $ref: '#/components/headers/Content-Encoding'
  schemas:
    create_prf_request:
      required:
        - physical_resources_type_id
        - physical_resources_subtype_id
        - msisdn_requestor
        - name_requestor
        - payment_method
        - payment_id
        - channel_transaction_id
        - shipping_info
      properties:
        physical_resources_type_id:
          description: ID of the physical resources type requested for fulfillment. List of ID type can be retrieved from API "GET /physical-resources-fulfillment/types"
          type: integer
          format: int32 
        physical_resources_subtype_id:
          description: ID of the physical resources subtype requested for fulfillment.  List of ID subtype can be retrieved from API "GET /physical-resources-fulfillment/types"
          type: integer
          format: int32
        msisdn_requestor:
          description: MSISDN of the order requester
          type: string
          maxLength: 16
        name_requestor:
          description: Name the order requester
          type: string
          maxLength: 32
        payment_method:
          description: Payment method can be used. Valid values 0= Link Aja, 1= Go pay
          type: integer
          format: int32
          enum:
            - 0
            - 1
        payment_id:
          description: Payment ID of the physical resources fulfillment request
          type: string
        channel_transaction_id:
          description:  Channel transaction ID
          type: string
        shipping_info:
          $ref: '#/components/schemas/shipping_info'
      example:
        physical_resources_type_id: 0
        physical_resources_subtype_id: 1
        msisdn_requestor: 6281212345678
        name_requestor: 'Agus Sender'
        payment_method: 0
        payment_id: 'TS3L12345678'
        channel_transaction_id: 'MYTSEL123456789'
        shipping_info:
          name: "Agus Sudrajat"
          msisdn: "6281312345678"
          email: "agus.sudrajat@gmail.com"
          address: "Sarinah Thamrin, Jl. M.H. Thamrin no.11"
          province: "DKI Jakarta"
          city: "Jakarta Pusat"
          kecamatan: "Menteng"
          kelurahan: "Babakan"
          postal_code: 10350
          additional_info: "Dekat Gedung XYZ"
          method: 0
          shipping_date: null
          shipping_arrival_date: null
    create_prf_response:
      allOf:
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              properties:
                order_id:
                  type: string
                  description: PRF Order ID that returned from API 'POST /physical-resource-fulfillment'
                order_state:
                  type: string
                  description: To be state of the PRF Order ID that want to be updated in the PRF system
                  enum:
                    - 'OPEN'
                    - 'PROCESSED'
                    - 'ON_DELIVERY'
                    - 'COMPLETED'
                    - 'CANCELLED'
                tdc_id:
                  type: integer
                  format: int32
                  description: TDC PIC ID that assigned to this order
        - $ref: '#/components/schemas/meta_response'
      example:
        data:
          order_id: "c1b9c176-37dd-45d9-8587-7964980119dc"
          order_state: "OPEN"
          tdc_id: 11000
        meta:
          took : 100
          status_code: 200
          status_desc: "success"
    update_prf_status_request:
      allOf:
        - type: object
          properties:
            tdc_id:
              type: integer
              description: TDC PIC ID that assigned the PRF Order ID. Value sent must same with TDC PIC ID assigned to order `pfOrderId`
        - $ref: '#/components/schemas/update_prf_status_request_exclusive'
    update_prf_status_request_exclusive:
      properties:
        ds_name:
          type: string
          description: Direct Sales PIC Name that assigned by TDC PIC ID. Mandatory to pass this when order state change from 'OPEN' to 'ON_DELIVERY'  Pass this value if want to assign a DC to PRF Order with ID `pfOrderId`. If the PRF Order already assigned with particular DC ID, it will be replaced with the new value pass in the API request, unless order state already `ON_DELIVER`, `COMPLETED`, `CANCELLED` 
        ds_msisdn:
          type: string
          description: Direct Sales MSISDN that assigned by TDC PIC ID. Mandatory to pass this when order state change from 'OPEN' to 'ON_DELIVERY'  Pass this value if want to assign a DC to PRF Order with ID `pfOrderId`. If the PRF Order already assigned with particular DC ID, it will be replaced with the new value pass in the API request, unless order state already `ON_DELIVER`, `COMPLETED`, `CANCELLED` 
        shipping_date:
          type: string
          format: date
          description: Date when the order will be shipped. Mandatory to pass this when order state change from 'OPEN' to 'ON_DELIVERY' 
        shipping_arrival_date:
          type: string
          format: date
          description: Date when the order delivered and received by shipping recipient. Mandatory to pass this when order state change from 'ON_DELIVERY' to 'COMPLETED'
        line_item_msisdn:
          type: string
          description: MSISDN that will be shipped by Direct Sales for a given `{prfOrderId}`. Mandatory to pass this when order state change from 'OPEN' to 'ON_DELIVERY' 
        order_notes:
          type: string
          maxLength: 32
          description: Additional notes when the shipping is failed to be delivered or the order is cancelled by the customer requestor.
        order_state:
          type: string
          description: To be state of the PRF Order ID that want to be updated in the PRF system. Pass this value if want to change state.
          enum:
            - 'OPEN'
            - 'ON_DELIVERY'
            - 'COMPLETED'
            - 'CANCELLED'
            - 'FAILED'
    update_prf_status_response:
      $ref: '#/components/schemas/create_prf_response'
    prf_detail_response:
      allOf:
        - type: object
          required:
            - data
          properties:
            data:
              $ref : '#/components/schemas/prf_detail'
        - $ref: '#/components/schemas/meta_response'
    prf_report_response:
      allOf:
        - type: object
          required:
            - data
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/prf_report"
        - $ref: '#/components/schemas/meta_response'
    list_prf_response:
      allOf:
        - type: object
          required:
            - data    
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/prf_detail'
        - $ref: '#/components/schemas/meta_response'
    list_prf_type_response:
      allOf:
        - type: object
          required: 
            - data
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/prf_type_detail'
        - $ref: '#/components/schemas/meta_response'
    list_shipping_options_response:
      allOf:
        - type: object
          required:
            - data    
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/shipping_options'
        - $ref: '#/components/schemas/meta_response'
    login_request:
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description:  Email of the TDC PIC
        password:
          type: string
          format: password
          description: Encoded value of the TDC PIC password (MD5 hashes)
      example:
        email:  'agus.sudrajat@gmail.com'
        password: '0403f2553b7d18874b872b8087dfb1b6'
    login_response:
      allOf:
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              properties:
                token: 
                  type: string
              example: 
        - $ref: '#/components/schemas/meta_response'
    logout_request:
      properties:
        email:
          type: string
          format: email
      example:
        email:  'agus.sudrajat@gmail.com'
    valid_tdc_response:
      allOf:
        - type: object
          required:
            - data
          properties:
            data:
              type: object
              properties:
                tdc_pic:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID of TDC PIC
                    name:
                      type: string
                      description: Name of the TDC PIC
                    msisdn:
                      type: string
                      description: Telkomsel MSISDN of the TDC PIC
                    description:
                      type: string
                      description: Short description about TDC PIC
                    cluster:
                      type: string
                      description: Delivery coverage area of the TDC PIC
                    is_active:
                      type: integer
                      description: Availabiity of the TDC. 0=not active, 1=active
                      enum:
                        - 0
                        - 1
        - $ref: '#/components/schemas/meta_response'
    meta_response:
      properties:
        meta: 
          type: object
          properties:
            took:
              type: integer
              format: int64
              description: Duration of the API processing the request in milliseconds
            status_code:
              type: integer
              description: Status code of the processing. Can be same with the HTTP status code returned 
            status_desc:
              type: string
              description: Status message of the processing. If error, it is filled with the error message 
          required:
          - took
          - status_code
          - status_desc
    prf_detail:
      properties:
        order_id:
          type: string
          description: PRF Order ID that returned from API 'POST /physical-resource-fulfillment'
        order_state:
          type: string
          description: To be state of the PRF Order ID that want to be updated in the PRF system
          enum:
            - 'OPEN'
            - 'ON_DELIVERY'
            - 'COMPLETED'
            - 'CANCELLED'
            - 'FAILED'
        order_notes:
          type: string
          description: Additional notes when the shipping is failed to be delivered or the order is cancelled by the customer requestor.
        is_order_out_of_sla:
          type: boolean
          description: Flag that indicates if the order is out of SLA. SLA is 3x24 hours count from date diff between current date and `created_at` for order with state `OPEN`, `ON_DELIVERY`
          enum:
            - true
            - false
        prf_type:
          description: PRF Type ID 
          allOf:
            - $ref: '#/components/schemas/prf_type'
            - type: object
              properties:
                subtype:
                  $ref: '#/components/schemas/prf_type'          
        tdc_id:
          type: integer
          format: int64
          description: TDC PIC ID that assigned to this order    
        ds_name:
          type: string
          description: Direct Sales Name PIC ID that assigned to this order    
        ds_msisdn:
          type: string
          description: Direct Sales MSISDN PIC ID that assigned to this order    
        created_at:
          type: string
          format: dateTime
          description: Date time when this PRF Request is created in the system
        msisdn_requestor:
          type: string
          description: MSISDN of the requester / creator of the PRF request
        name_requestor:
          type: string
          description: Name of the requester / creator of the PRF request
        payment_method:
          type: integer
          description: Coded value of the payment method chosen when creating PRF request
        payment_id:
          type: string
          description: Payment ID returned by the selected payment method provider
        payment_amount:
          type: integer
          format: int32
          description: Total final payment amount of the order including shipping fee, discount, etc.
        shipping_info:
          allOf:
            - $ref: '#/components/schemas/shipping_info'
            - type: object
              properties:  
                method_name:
                  type: string
                  description: Delivery method of the physical resources
                  enum: ["tdc"]  
      example:
        order_id: "c1b9c176-37dd-45d9-8587-7964980119dc"
        order_state : "FAILED"
        order_notes: 'Gagal kirim. Orang tidak ada di rumah'
        is_order_out_of_sla: true
        prf_type:
          id: 0
          name: sim-card
          subtype:
            id: 1
            name: prepaid
        tdc_id: 1100
        ds_name: 'Agus Direct Sales'
        ds_msisdn: '6281287654321'
        created_at: "2020-02-19T14:11:32Z"
        msisdn_requestor: "0281297053302"
        name_requestor: 'Agus Sender'
        payment_method: 0
        payment_id : "TS3L0212713458"
        payment_amount: 17000
        shipping_info:
          name: "Agus Sudrajat"
          msisdn: "081312345678"
          email: "agus.sudrajat@gmail.com"
          address: "Sarinah Thamrin, Jl. M.H. Thamrin no.11"
          province: "DKI Jakarta"
          city: "Jakarta Pusat"
          kecamatan: "Menteng"
          kelurahan: "Babakan"
          postal_code: 10350
          additional_info: "Dekat Gedung XYZ"
          method_id: 0
          method_name : "tdc"
          shipping_date: '2020-03-29'
          shipping_arrival_date: '2020-04-01'
    prf_type:
      properties:
        id: 
          type: integer
          format: int32
          description: Generated ID of the PRF type/subtype in the system
        name:
          type: string
          description: Short name of the PRF PRF type/subtype
          maxLength: 32
    prf_type_detail:
      properties:
        prf_type: 
          allOf:
          - $ref: '#/components/schemas/prf_type'
          - type: object 
            properties:
                subtype:
                  type: array
                  items:
                    $ref: '#/components/schemas/prf_type'
      example:
        id: 0
        name: sim-card
        subtype:
          - id: 1
            name: prepaid
    prf_report:
        properties:
          aggregate_scope:
              type: string
              description: Period scope of the aggregated values if aggregated within period monthly, weekly, or daily. 
              enum:
                - daily
                - monthly
                - yearly
              example: monthly
          date_value:
              type: string
              description: |
                Value of the scope period, extracted from the date filter applied when aggregating the report. 
                * If scope is `daily` then return `day of month` value of the date filter
                * If scope is `monthly` then return `month` value of the date filter
                * If scope is `yearly` then return `year of month` value of the date filter
              example: '03'
          performance:
              type: array
              description: Aggregated value of the orders group by the order status
              items:
                  properties:
                    order_state:
                        type: string
                        enum:
                          - OPEN
                          - ON_DELIVERY
                          - COMPLETED
                          - FAILED
                          - CANCELLED
                        example: OPEN
                    total:
                        type: integer
                        example: 125                     
    shipping_info:
      description: Shipping information of the order
      type: object
      properties:
        name:
          description: Name of the recipient
          type: string
          maxLength: 32
        msisdn:
          description: MSISDN number of the recipient
          type: string
          maxLength: 16
        email:
          description: Email address of the recipient
          type: string
          maxLength: 32
        address:
          description: Detail recipient address
          type: string
          maxLength: 32
        province:
          description: Province name of the recipient
          type: string
          maxLength: 32
        city:
          description: City name of the recipient
          type: string
          maxLength: 32
        kecamatan:
          description: Kecamatan name of the recipient
          type: string
          maxLength: 32
        postal_code:
          description: Postal / ZIP code of the recipient
          type: string
          maxLength: 12
        additional_info:
          description: Additional information for the shipping
          type: string
          maxLength: 255
        shipping_date:
          description: Date when the order being shipped
          type: string
          format: date
        shipping_arrival_date:
          description: Date when the order received by the customer
          type: string
          format: date
        method:
          description: Shipping method used to deliver. Valid values 0=TDC
          type: integer
          format: int32
          enum:
          - 0
    shipping_options:
      description: Shipping service options
      properties:
        courier_id:
          type: integer
          format: int32
          description: ID of the courier
        courier_name:
          type: string
          description: Name of the courier
        description:
          type: string
          description: Short description about the courier
        coverage:
          type: array
          description: Shipping coverage of the courier 
          items:
            $ref: '#/components/schemas/shipping_coverage'
        services:
          type: array
          description: Shipping services type provided by the courier 
          items: 
            $ref: '#/components/schemas/shipping_service'
      example:
        courier_id: 1
        courier_name: TDC
        description: Telkomsel Delivery Center 
        coverage: 
          - province: DKI Jakarta
            city: Jakarta Selatan
          - province: DKI Jakarta
            city: Jakarta Timur  
        services:
          -  name: tdc-pic-ds
             sla: '72'
             sla_unit: 'jam'
    shipping_coverage:
      description: Shipping service coverage area
      properties:
        province:
            type: string
            description: Province name
        city:
            type: string
            description: City name
    shipping_service:
      description: Shipping service type of a courier
      properties:
        name:
          type: string
          description: Courier service name
        sla:
          type: string
          description: SLA of the courier service until deliver the physical resources to customer
        sla_unit:
          type: string
          description: SLA unit of the courier service until deliver the physical resources to customer 
  securitySchemes:
    basicAuth:
      type: http
      scheme: Basic
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  links: {}
  callbacks: {}
security:
  - basicAuth: []