openapi: 3.0.0

servers:
# Added by API Auto Mocking Plugin
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CIBG/Emailvalidatie/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CIBG/Emailservice/1.0.0
  - url: http://cibg-api-egw-dev.mso.mhsrijk.nl
  - url: http://cibg-api-egw-test.mst.mhsrijk.nl
  - url: http://cibg-api-egw-acc.frd.otassonet.local
  - url: http://cibg-api-egw-prod.frd.ssonet.nl
info:
  description: Service om te valideren of het opgegeven emailadres uitgelezen kan worden door middel van het sturen van een tijdelijke token.
  version: "1.0.0"
  title: Emailvalidatie
  contact:
    email: dienstpostbusCIBG-ICTKoppelvlakken@minvws.nl
paths:
  /cgs/emlvl/1/api/emailvalidation/generate:
    post:
      summary: Verstuur een token naar het emailadres
      description: |
        'Verstuur een tijdelijke token naar het opgegeven emailadres.'
      responses:
        '202':
          description: 'mailbericht is succesvol naar de mailservice verstuurd'
        '400':
          description: 'invalide input'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Bad Request'
                  reason: 'Invalid Schema ($.emailAddress: does not match the regex pattern ^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$)'
        '429':
          description: 'te veel pogingen gemaakt binnen korte tijd'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Too Many Requests'
                  reason: 'nl.cibg.integratieteam.cgs.exception.QuotaExceededException-Address 10.136.107.175 has already tried 6 times.'
        '500':
          description: 'onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Internal Server Error'
                  reason: 'Routing failure'
              
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tokenrequest'

        description: Mail bericht
  /cgs/emlvl/1/api/emailvalidation/validate:
    post:
      summary: Valideer token
      description: |
         'Valideer het token dat naar het emailadres is verstuurt'
      responses:
        '204':
          description: 'token is succesvol gevalideerd'
        '400':
          description: 'invalide input'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Bad Request'
                  reason: 'Invalid Schema ($.emnailAddress: does not match the regex pattern ^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$)'
        '403':
          description: 'token komt niet overeen of kan niet gevonden worden'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Forbidden'
                  reason: 'Token is not valid'
        '429':
          description: 'te veel pogingen gemaakt binnen korte tijd'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Too Many Requests'
                  reason: 'nl.cibg.integratieteam.cgs.exception.QuotaExceededException-Address 10.136.107.175 has already tried 6 times.'
        '500':
          description: 'onverwachte fout'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cibgFault'
              example:
                fault:
                  code: 'Internal Server Error'
                  reason: 'Routing failure'
              
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tokenvalidation'
        description: Token validatie        
  /cgs/api/1/health/ping:
    get:
      summary: Controleer of service operationeel is
      responses:
        '200':
          description: Service is operationeel
components:
  schemas:
    tokenrequest:
      type: object
      properties:
        sourceIpAddress:
          $ref: '#/components/schemas/sourceIpAddress'
        emailadres:
          $ref: '#/components/schemas/emailAddress'
        applicationCode:
          $ref: '#/components/schemas/applicationCode'
    tokenvalidation:
      type: object
      properties:
        sourceIpAddress:
          $ref: '#/components/schemas/sourceIpAddress'
        emailadres:
          $ref: '#/components/schemas/emailAddress'
        applicationCode:
          $ref: '#/components/schemas/applicationCode'
        token:        
          type: string
          description: 'token welke naar het emailadres is gestuurd en gevalideerd moet worden'
          pattern: '\\d{6}'
          example: '123456'
    cibgFault:
      type: object
      properties:
        fault:
          type: object
          properties:
            code:
              type: string
              example: 'ErrorCode'
            reason:
              type: string
              example: 'Reden van fout'
            detail:
              type: string
              example: 'Extra informatie over fout'
    sourceIpAddress:
      type: string
      description: 'IP-Address van de gebruiker waarmee gevalideerd wordt hoe vaak een poging wordt uitgevoerd om een token te versturen.'
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
      example: '194.195.196.197'
    emailAddress:
      type: string
      description: 'Emailadres dat gevalideerd moet worden.'
      format: email
      minLength: 1
      maxLength: 255
      pattern: "^(?=.{1,254}$)(?=.{1,64}@)[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+(?:.[a-zA-Z0-9!#$%&'*+\/=?^_`{|}~-]+)*@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
      example: info@cibg.nl
    applicationCode:
      type: string
      description: 'vijf-letterige afkorting van het systeem waarvoor de validatie wordt uitgevoerd. Validatie is altijd voor een specifiek systeem.'
      minLength: 3
      maxLength: 5
      example: 'metza'
