openapi: 3.0.0
info:
  title: SLAPP
  version: '1.0'
  description: ''
servers:
  - url: 'http://bids.jetspizza.com'
paths:
  /general_stores:
    get:
      summary: Retrieve Store Data
      tags: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      count:
                        type: integer
                      next:
                        type: string
                        description: |
                          Link to the next set of results adds quey param of page number
                      previous:
                        type: string
                        description: Link to to last page of results
                  Data:
                    type: object
                    properties:
                      id:
                        type: string
                      distance:
                        type: string
                      groups:
                        type: array
                        items:
                          type: string
                      hour:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      name:
                        type: string
                      address:
                        type: string
                      address 2:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      timezone:
                        type: string
                      zipcode:
                        type: string
                      owner name:
                        type: string
                      owner_phone:
                        type: string
                      store_phone:
                        type: string
                      is_active:
                        type: boolean
                      alternte_id:
                        type: string
                      ordering_platform:
                        type: string
                      latitude:
                        type: string
                      longitude:
                        type: string
                      ordertalk_abbrv:
                        type: string
                      is_dst:
                        type: string
                      ordering_url:
                        type: string
                      keep_gmb_updates:
                        type: string
              examples:
                'Example with return, with some data redacted':
                  value:
                    meta:
                      count: 416
                      next: 'http://api-storeadminprod.6viuccxtmz.us-east-2.elasticbeanstalk.com/general_stores?page=2'
                      previous: null
                    data:
                      - id: co002
                        distance: null
                        groups: []
                        hour: '10:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:31.201905Z'
                        updated_at: '2019-02-08T19:45:39.546750Z'
                        name: CO-002
                        address_1: 8176 S Holly St
                        address_2: ''
                        city: Centennial
                        state: CO
                        timezone: America/Denver
                        zip_code: '80122'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '3037415387'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 39.5680533
                        longitude: -104.922929
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://ordering.jetspizza.com/?uniqueStoreIdentifier=CO002'
                        keep_gmb_update: true
                      - id: mi035
                        distance: null
                        groups: []
                        hour: '10:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:30.894089Z'
                        updated_at: '2018-12-07T18:43:25.602950Z'
                        name: MI-035
                        address_1: 151 N Eton St
                        address_2: ''
                        city: Birmingham
                        state: MI
                        timezone: America/Detroit
                        zip_code: '48009'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '2486377549'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 42.548363
                        longitude: -83.196438
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://orderjets.hungerrush.com/Order/Menu/1'
                        keep_gmb_update: true
                      - id: nc012
                        distance: null
                        groups: []
                        hour: '10:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:31.559175Z'
                        updated_at: '2018-12-07T18:50:30.736928Z'
                        name: NC-012
                        address_1: 1229 Concord Pkwy N
                        address_2: ''
                        city: Concord
                        state: NC
                        timezone: America/New_York
                        zip_code: '28025'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '7047215387'
                        is_active: false
                        alternate_id: ''
                        ordering_platform: order_talk
                        latitude: 35.4319404
                        longitude: -80.6061584
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: false
                        ordering_url: ''
                        keep_gmb_update: true
                      - id: mi013
                        distance: null
                        groups: []
                        hour: '10:00 AM - 12:00 AM'
                        created_at: '2017-03-27T12:44:35.033316Z'
                        updated_at: '2019-02-26T17:55:00.152251Z'
                        name: MI-013
                        address_1: 30114 Harper
                        address_2: ''
                        city: St. Clair Shores
                        state: MI
                        timezone: America/Detroit
                        zip_code: '48082'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '5864150990'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 42.515534
                        longitude: -82.898535
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://ordering.jetspizza.com/?uniqueStoreIdentifier=MI013'
                        keep_gmb_update: true
                      - id: fl026
                        distance: null
                        groups: []
                        hour: '11:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:30.965621Z'
                        updated_at: '2018-12-12T13:34:13.194505Z'
                        name: FL-026
                        address_1: 8721 State Rd 70 East
                        address_2: ''
                        city: Bradenton
                        state: FL
                        timezone: America/New_York
                        zip_code: '34202'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '9417395387'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 27.43903
                        longitude: -82.450041
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://orderjets.hungerrush.com/order/menu/99'
                        keep_gmb_update: true
                      - id: mi136
                        distance: null
                        groups: []
                        hour: '11:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:30.807339Z'
                        updated_at: '2019-04-03T16:49:39.531391Z'
                        name: MI-136
                        address_1: 590 Columbia Ave W
                        address_2: ''
                        city: Battle Creek
                        state: MI
                        timezone: America/Detroit
                        zip_code: '49015'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '2695650800'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 42.2989105
                        longitude: -85.2098179
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://ordering.jetspizza.com/?uniqueStoreIdentifier=MI136'
                        keep_gmb_update: true
                      - id: mi009
                        distance: null
                        groups: []
                        hour: '11:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:31.446459Z'
                        updated_at: '2018-12-12T14:27:58.269370Z'
                        name: MI-009
                        address_1: 230 W. 14 Mile Rd
                        address_2: ''
                        city: Clawson
                        state: MI
                        timezone: America/Detroit
                        zip_code: '48017'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '2482884488'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 42.533364
                        longitude: -83.150317
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://orderjets.hungerrush.com/Order/Menu/11'
                        keep_gmb_update: true
                      - id: ky002
                        distance: null
                        groups: []
                        hour: '11:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:32.491237Z'
                        updated_at: '2019-05-09T14:33:59.132893Z'
                        name: KY-002
                        address_1: 3420 Valley Plaza Pkwy
                        address_2: ''
                        city: Ft Wright
                        state: KY
                        timezone: America/Kentucky/Louisville
                        zip_code: '41017'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '8593444400'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 39.0371192
                        longitude: -84.536983
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://ordering.jetspizza.com/?uniqueStoreIdentifier=KY002'
                        keep_gmb_update: true
                      - id: oh040
                        distance: null
                        groups: []
                        hour: ''
                        created_at: '2017-05-17T17:19:37.201832Z'
                        updated_at: '2019-05-09T14:37:04.153083Z'
                        name: OH-040
                        address_1: 7916 S. Mason Montgomery Rd
                        address_2: ''
                        city: Mason
                        state: OH
                        timezone: EST
                        zip_code: '45040'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '2163281900'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 39.323843
                        longitude: -84.312
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://ordering.jetspizza.com/?uniqueStoreIdentifier=OH040'
                        keep_gmb_update: true
                      - id: tn026
                        distance: null
                        groups: []
                        hour: '11:00 AM - 11:00 PM'
                        created_at: '2017-03-27T12:44:30.694711Z'
                        updated_at: '2018-12-12T17:45:14.891662Z'
                        name: TN-026
                        address_1: 3534 Murfreesboro Pike
                        address_2: ''
                        city: Antioch
                        state: TN
                        timezone: America/Chicago
                        zip_code: '37013'
                        owner_name: ''
                        owner_phone: ''
                        store_phone: '6156415333'
                        is_active: true
                        alternate_id: ''
                        ordering_platform: other
                        latitude: 36.0528431
                        longitude: -86.6171708
                        ordertalk_abbrv: null
                        is_dst: false
                        has_app_ordering: true
                        ordering_url: 'https://orderjets.hungerrush.com/Order/Menu/101'
                        keep_gmb_update: true
          description: ''
      operationId: get-general_stores
      description: Returns store information for all stores with page size of 50
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: Store id ie. mi009
        - schema:
            type: string
          in: query
          name: distance
          description: 'Distance in miles, if no point is provided retreives same result as no-oarameter'
        - schema:
            type: string
          in: query
          name: point
          description: Comma separated Lat/Long
        - schema:
            type: integer
          in: query
          name: page
          description: Which page number of results you want to recieve
  /app_build:
    get:
      summary: Get App Build Information
      parameters:
        - schema:
            type: string
          in: query
          name: app
          description: '{ordering, bid}'
        - schema:
            type: boolean
          in: query
          name: is_active
        - schema:
            type: string
          in: query
          name: order_by
          description: '{-version, -platform, -app}'
        - schema:
            type: string
          in: query
          name: version_gt
        - schema:
            type: string
          in: query
          name: kind
          description: '{release, develop, preview}'
        - schema:
            type: string
          in: query
          name: platform
          description: '{unknown, Ios, android, windows}'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      count:
                        type: integer
                      next:
                        type: string
                      prev:
                        type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      app:
                        type: string
                      name:
                        type: string
                      description:
                        type: string
                      version:
                        type: string
                      platform:
                        type: string
                      is_mandatory:
                        type: boolean
                      is_active:
                        type: boolean
                      kind:
                        type: string
                      release_note:
                        type: string
              examples:
                standard:
                  value:
                    meta:
                      count: 3
                      next: null
                      previous: null
                    data:
                      - id: 2
                        created_at: '2018-08-01T08:38:59.603362Z'
                        updated_at: '2018-08-01T08:38:59.603394Z'
                        app: bid
                        name: Bid
                        description: ''
                        version: 1.2.2
                        platform: ios
                        is_active: false
                        is_mandatory: false
                        kind: release
                        release_note: provision profile change
                      - id: 3
                        created_at: '2018-12-08T03:58:13.517413Z'
                        updated_at: '2018-12-08T03:58:13.517450Z'
                        app: ordering
                        name: Ordering
                        description: ''
                        version: 1.5.0
                        platform: ios
                        is_active: true
                        is_mandatory: true
                        kind: release
                        release_note: ''
                      - id: 4
                        created_at: '2018-12-09T00:57:22.331112Z'
                        updated_at: '2018-12-09T00:57:22.331146Z'
                        app: ordering
                        name: Ordering
                        description: Ordering app
                        version: 1.5.0
                        platform: android
                        is_active: true
                        is_mandatory: true
                        kind: release
                        release_note: Update
      description: This endpoint is used by the mobile app to check the latest version of the app.
    parameters: []
  '/general_stores/{storeid}/normal_hours':
    
    parameters:
      - schema:
          type: string
        name: storeid
        in: path
        required: true
    get:
      summary: Get normal hours for a store
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      count:
                        type: integer
                      next:
                        type: string
                      prev:
                        type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      create_at:
                        type: string
                      updated_at:
                        type: string
                      day_of_week:
                        type: string
                      delivery_open_at:
                        type: string
                      delivery_close_at:
                        type: string
                      open_at:
                        type: string
                      close_at:
                        type: string
                      store:
                        type: string
              examples:
                /mi009/normal_hours:
                  value:
                    meta:
                      count: 7
                      next: null
                      previous: null
                    data:
                      - id: 9528
                        created_at: '2017-03-27T12:44:31.460105Z'
                        updated_at: '2017-03-27T12:44:31.460127Z'
                        day_of_week: monday
                        delivery_open_at: '11:00:00'
                        delivery_close_at: '22:00:00'
                        open_at: '11:00:00'
                        close_at: '22:00:00'
                        store: mi009
                      - id: 9529
                        created_at: '2017-03-27T12:44:31.460210Z'
                        updated_at: '2017-03-27T12:44:31.460236Z'
                        day_of_week: tuesday
                        delivery_open_at: '11:00:00'
                        delivery_close_at: '22:00:00'
                        open_at: '11:00:00'
                        close_at: '22:00:00'
                        store: mi009
                      - id: 9530
                        created_at: '2017-03-27T12:44:31.460298Z'
                        updated_at: '2017-03-27T12:44:31.460310Z'
                        day_of_week: wednesday
                        delivery_open_at: '11:00:00'
                        delivery_close_at: '22:00:00'
                        open_at: '11:00:00'
                        close_at: '22:00:00'
                        store: mi009
                      - id: 9531
                        created_at: '2017-03-27T12:44:31.460369Z'
                        updated_at: '2017-03-27T12:44:31.460392Z'
                        day_of_week: thursday
                        delivery_open_at: '11:00:00'
                        delivery_close_at: '22:00:00'
                        open_at: '11:00:00'
                        close_at: '22:00:00'
                        store: mi009
                      - id: 9532
                        created_at: '2017-03-27T12:44:31.460448Z'
                        updated_at: '2017-03-27T12:44:31.460459Z'
                        day_of_week: friday
                        delivery_open_at: '11:00:00'
                        delivery_close_at: '23:00:00'
                        open_at: '11:00:00'
                        close_at: '23:00:00'
                        store: mi009
                      - id: 9533
                        created_at: '2017-03-27T12:44:31.460526Z'
                        updated_at: '2017-03-27T12:44:31.460537Z'
                        day_of_week: saturday
                        delivery_open_at: '11:00:00'
                        delivery_close_at: '23:00:00'
                        open_at: '11:00:00'
                        close_at: '23:00:00'
                        store: mi009
                      - id: 9534
                        created_at: '2017-03-27T12:44:31.460588Z'
                        updated_at: '2017-03-27T12:44:31.460598Z'
                        day_of_week: sunday
                        delivery_open_at: '12:00:00'
                        delivery_close_at: '22:00:00'
                        open_at: '12:00:00'
                        close_at: '22:00:00'
                        store: mi009
      operationId: get-general_stores-storeid-normal_hours
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: |
            Page size of return
      description: Returns normal hours for a store location
  '/general_stores/{storeid}/special_hours':
    parameters:
      - schema:
          type: string
        name: storeid
        in: path
        required: true
    get:
      summary: Get Special Hours for a store
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      prev:
                        type: string
                      count:
                        type: integer
                      next:
                        type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      for_date:
                        type: string
                      is_close:
                        type: boolean
                      is_every_year:
                        type: boolean
                      delivery_open_at:
                        type: string
                      delivery_close_at:
                        type: string
                      close_at:
                        type: string
                      store:
                        type: string
                        description: Id of the store
              examples:
                /mi009/special_hours:
                  value:
                    meta:
                      count: 2
                      next: null
                      previous: null
                    data:
                      - id: 1522
                        created_at: '2019-11-20T18:08:36.565362Z'
                        updated_at: '2019-11-20T18:08:36.565391Z'
                        for_date: '0001-12-25'
                        is_close: true
                        is_every_year: true
                        delivery_open_at: '00:00:00'
                        delivery_close_at: '00:00:00'
                        open_at: '00:00:00'
                        close_at: '00:00:00'
                        store: mi009
                      - id: 1523
                        created_at: '2019-11-20T18:08:36.566580Z'
                        updated_at: '2019-11-20T18:08:36.566602Z'
                        for_date: '2019-11-28'
                        is_close: true
                        is_every_year: false
                        delivery_open_at: '00:00:00'
                        delivery_close_at: '00:00:00'
                        open_at: '00:00:00'
                        close_at: '00:00:00'
                        store: mi009
      operationId: get-general_stores-storeid-special_hours
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: page size of return
      description: returns special hours for a store location
  /system/app_feedback:
    parameters: []
    post:
      summary: Send Feedback from mobile app
      operationId: post-system-app_feedback
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value:
                  full_name: Full customer name
                  email: email@email.com
                  text: this is my feedback.
                  debug_info:
                    device_platform: 'cordova, core'
                    device_version: null
                    device_model: null
                    device_manufacturer: null
                    loaded_pages: HomePage
      description: Send app-feedback from mobile app
  '/general_stores/{storeid}':
    summary: Get information for a specific store
    parameters:
      - schema:
          type: string
        name: storeid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      distance:
                        type: string
                      groups:
                        type: array
                        items:
                          type: string
                      hour:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      name:
                        type: string
                      address_1:
                        type: string
                      address_2:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      timezone:
                        type: string
                      zip_code:
                        type: string
                      owner_name:
                        type: string
                      owner_phone:
                        type: string
                      store_phone:
                        type: string
                      is_active:
                        type: boolean
                      alternate_id:
                        type: string
                      ordering_platform:
                        type: string
                      latitude:
                        type: string
                      longitude:
                        type: string
                      ordertalk_abbrv:
                        type: string
                      is_dst:
                        type: string
                      has_app_ordering:
                        type: boolean
                      ordering_url:
                        type: string
                      keep_gmb_update:
                        type: boolean
              examples:
                mi049:
                  value:
                    data:
                      id: mi049
                      distance: null
                      groups: []
                      hour: '11:00 AM - 12:00 AM'
                      created_at: '2017-03-27T12:44:35.474428Z'
                      updated_at: '2019-05-07T16:38:05.308322Z'
                      name: MI-049
                      address_1: 6641 Orchard Lake Rd
                      address_2: ''
                      city: West Bloomfield
                      state: MI
                      timezone: America/Detroit
                      zip_code: '48322'
                      owner_name: ''
                      owner_phone: ''
                      store_phone: ''
                      is_active: true
                      alternate_id: ''
                      ordering_platform: other
                      latitude: 42.540398
                      longitude: -83.360606
                      ordertalk_abbrv: null
                      is_dst: false
                      has_app_ordering: true
                      ordering_url: ''
                      keep_gmb_update: true
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                mi049:
                  value:
                    data:
                      id: mi049
                      distance: null
                      groups: []
                      hour: '11:00 AM - 12:00 AM'
                      created_at: '2017-03-27T12:44:35.474428Z'
                      updated_at: '2019-05-07T16:38:05.308322Z'
                      name: MI-049
                      address_1: 6641 Orchard Lake Rd
                      address_2: ''
                      city: West Bloomfield
                      state: MI
                      timezone: America/Detroit
                      zip_code: '48322'
                      owner_name: ''
                      owner_phone: ''
                      store_phone: '2487370770'
                      is_active: true
                      alternate_id: ''
                      ordering_platform: other
                      latitude: 42.540398
                      longitude: -83.360606
                      ordertalk_abbrv: null
                      is_dst: false
                      has_app_ordering: true
                      ordering_url: 'https://ordering.jetspizza.com/?uniqueStoreIdentifier=13506'
                      keep_gmb_update: true
      operationId: get-general_stores-storeid
      description: Returns data for a single store
components:
  schemas: {}
